### ISSUE TITLE
Working with pre-designed columns

### ISSUE THREAD

**Issue by desarrollo03TR** [davidegironi/advanceddatagridview#10]
Hi! I have an AdvancedDGV with columns pre-designed (using the VS designer) and I cannot make datetime and int columns works with sorting and filtering, it works like text sort/filter.

Is there any way to achieve custom sorting/filtering for pre-designed  columns?

**Comment by davidegironi** [comment]
Hello, you have to attach the FilterStringChanged and SortStringChanged event. Take a look at the FormMain code for an example.
