### ISSUE TITLE
Do you have a tutorial on how to start a new Winform with ADGV?

### ISSUE THREAD

**Issue by fredatgithub** [davidegironi/advanceddatagridview#100]
Do you have a tutorial on how to start a new Winform with ADGV?
I saw a sample project in the solution but I don't see a control.

**Comment by davidegironi** [comment]
Hello, I don't have any tutorial.
After you add the library to your reference manually or using nuget, you should see it on the left side. Then you can drag it like you do with the Microsoft DataGridView.
Find below an example.
![Capture_ADGV_VS_Toolbox](https://user-images.githubusercontent.com/1426098/211074805-f6c55fd2-cc64-47fb-a843-7e0526b2e682.JPG)

**Comment by fredatgithub** [comment]
Very good
thanks
