### ISSUE TITLE
Cumulative filtering does not seem to work

### ISSUE THREAD

**Issue by louieo** [davidegironi/advanceddatagridview#102]
I have a data source successfully hooked up to the grid and filtering fine. I am handling the FilterStringChanged event but when multiple filters have been applied (against more than one column), FilterString on the component itself is being overwritten with only the filter string of the column most recently changed. Is there a way to apply multiple filters? I have tried keeping track of filters myself as they are applied and this works, except when a filter is unapplied, there is no way to identify which column filter I should remove. Thanks!

**Comment by louieo** [comment]
This is related to using a list as DataSource. It was easier for me to make a DataTable and then the filtering worked as expected with much less tricky code. Closing this :)

**Comment by davidegironi** [comment]
;)
