### ISSUE TITLE
automatically disable Filter/Sort for unbound Columns OR let them sort/filter by ItemValue.ToString

### ISSUE THREAD

**Issue by TraglDotNet** [davidegironi/advanceddatagridview#103]
Hello.

I'd like using the AdvancedDataGridView in my little Project. But now i'm struggeling with the following constellation:

ADGV With typed DataTable As DataSource: Filtering and Sorting works nicely.
Added some unbound Columns and Filling them with some Values during the RowPrepaint-Event.

Filtering and Sorting for those Columns ends in Crashing. Would it be possible to turn filtering/sorting automatically off?
My actual Workaround for this:
` 
<Extension>
Friend Sub DisableFilterAndSortForUnboundColumns(aDgv As AdvancedDataGridView)
        aDgv.ColumnsX.Where(Function(x) Not x.IsDataBound).ForEach(Sub(col) aDgv.DisableFilterAndSort(col))
End Sub
`

OR (i think the better way): Would it be possible to Sort the unbound-column-items Value.Tostring?

**Comment by davidegironi** [comment]
Hello,
I don't fully understand what you are trying to do. If you can build up a stand-alone sample project I can take a look at it as soon as I've time do spend on.

**Comment by TraglDotNet** [comment]
Hi, 

here's a small Test-Project which shows the "Problem". As the Screenshot shows, the green section can be filtered (bound to DataTable), the red section shows an Error (not bound). I also added my small extension to turn filtering for unbound columns on or off. I hope it's unterstandable now :-)

[aDgvTest01.zip](https://github.com/davidegironi/advanceddatagridview/files/10949238/aDgvTest01.zip)

![Screenshot 2023-03-11 200023](https://user-images.githubusercontent.com/127254126/224507205-2555a3ec-1628-45f9-889a-35b5608ef011.png)
![Screenshot 2023-03-11 200243](https://user-images.githubusercontent.com/127254126/224507207-f7aac91d-049a-4a58-be37-d4b4a8691576.png)

**Comment by davidegironi** [comment]
Thanks, now I get what you mean.
Mixed column mode does not work.
What I suggest you is to add a fields to the DataSet loaded, or the XML file. Than work on that field. Otherwise you have to disable the filtering and sorting like you are doing.
