### ISSUE TITLE
Error filtering column of Type Object with mixed Types in the rows

### ISSUE THREAD

**Issue by Inaciomcr** [davidegironi/advanceddatagridview#104]
Hi,

I'm trying to filter a column of Type Object that has rows of Type Datetime and String and when i click on the filter it gives the following error in the function "BuildNodes" of the class MenuStrip, [line 1108](https://github.com/davidegironi/advanceddatagridview/blob/5df4657c0e7faf4cca2f6d81f92568ee461c26a0/AdvancedDataGridView/MenuStrip.cs#L1108): "The object must be of type DateTime.".
In the follwing picture the error occours in the "Date" column:
![imagem](https://user-images.githubusercontent.com/1430808/224702592-f4880eb1-527e-437a-86d9-1c98679968dd.png)

In excel when you have a mix of dates and strings in one column the filter can handle both types and create the grouped dates and also adding the strings to the list:
![imagem](https://user-images.githubusercontent.com/1430808/224702847-2caa3918-28dc-4d1f-ad74-d3886f66c413.png)

If I format the column as string the dates aren't grouped like in the excel.

**Comment by davidegironi** [comment]
Hello, I'm sorry but at this time you can't mix types.
