### ISSUE TITLE
advanceddatagridview from Nuget can not be used in Visual Studio 17.5.4

### ISSUE THREAD

**Issue by jory999** [davidegironi/advanceddatagridview#108]
have to rollback to 17.5.3

**Comment by davidegironi** [comment]
Hello. Can you clarify? Is it a VS error or a ADGV error?

**Comment by jory999** [comment]
I think it's VS error,when rollback vs to previous version 17.5.3,ADGV work ok.
but I can't conclusively determine why

**Comment by elachlan** [comment]
Related: https://github.com/dotnet/winforms/issues/9026

Please see: https://github.com/microsoft/winforms-designer-extensibility/

**Comment by davidegironi** [comment]
Thank you for making me notice this. I'm out for vacation, as soon as I'll have some spare time I'll investigate this issue deeper. I've never heard before about that winforms designer extensibility.
I've give it a first read. AGDV should not be affected, cause it haven't got nothing to show as UI in design time
"...If your control requires a UI which is based on a type-converter and therefore, shown in the context of the Property Browser (like Enums or dedicated items to show in a property grid’s property grid cell ComboBox), your UI will be supported by the new designer model out of the box.

If your control requires a UI, which shows up as part of the control (like custom painted adorners or Action Lists) at design time, then you would need to write your control library against the WinForms Designer SDK, but you don’t need to take care about round-tripping data to the Server process. Everything from the Developer’s perspective seems to actually be done server-side, and you can reuse most of the existing control designer Code..."

Said this, I'll investigate further. Meanwhile if someone solve this issue please write it here.
Can I ask you which .NET version are you trying to add the library too?
Have you try adding it by reference dll?

**Comment by jory999** [comment]
Thank you for your excellent work, I'm using .NET 6.0

**Comment by jory999** [comment]
Thank you for your excellent work, I'm using .NET 6.0.
when I update vs from 17.5.3 to 17.5.4, ADGV unnormal ,
before update vs evevything is OK

**Comment by davidegironi** [comment]
Hello, I've try with my 17.5.4 version and I've no problem (both .NET 6 and .NET7 and .NET framework ) - Windows 10 x64. See attached sample projects.
![Capture](https://user-images.githubusercontent.com/1426098/234501360-ab2ee90a-599b-4fa1-b8fb-3022dfade850.PNG)
[vs1754_adgv_test.zip](https://github.com/davidegironi/advanceddatagridview/files/11330154/vs1754_adgv_test.zip)

Have you got a log of the installation?
