### ISSUE TITLE
Error while trying to create multiple ADGV dynamically

### ISSUE THREAD

**Issue by layla-oli** [davidegironi/advanceddatagridview#109]
Greetings!

We are working on a code that dynamically creates multiple tabs in a tab control. It also dynamically creates DGVs by injecting them into the tabs. The procedure works by using standard DGV. However, when replacing DGV with ADGV  (by performing the procedure of assigning the data table to the binding source data source and binding the source to the ADGV data source), the code picks up the following exception:

 
![image](https://user-images.githubusercontent.com/60330922/235167578-233a2cc5-c99c-4519-8801-076f2e9ffdd7.png)

We found a temporary solution: inserting the data sources assignment into a Try-Catch. The data assignment completes correctly, so much so that the system runs fine when it places the assignment within the Try-Catch. All tabs will then show the ADGVs and their tables correctly. However, this is still a workaround. Additionally, I should mention that we're are working under .NET 4.5.2.

We would appreciate any hints to debug and resolve the error in the original procedure.

Below are the relevant segments of the original affected code:

```
foreach(var elemento in resultsList)
            {
                var tab = new TabPage();
                tab.Name = "tab_" + elemento.Key;
                tab.Text = elemento.Key;
                tab_Results.Controls.Add(tab);
                tab.Padding = new Padding(4, 4, 4, 4);
                tab.BackColor = Color.White;
                AdvancedDataGridView dgv = new AdvancedDataGridView();
                dgv.ReadOnly = true;
                tab.Controls.Add(dgv);
                createDGV(elemento, dgv);
            }
public void createDGV(KeyValuePair<string, object> elemento, AdvancedDataGridView dgv)
        {
            dgv.Dock = DockStyle.Fill;
            DataTable dt = new DataTable();
           
            dt = (DataTable)elemento.Value;

            BindingSource bindingSource = new BindingSource();
            try
            {
                bindingSource.DataSource = dt;
                dgv.DataSource = bindingSource; // Here's the error
            }
            catch { }

            dgv.RowHeadersVisible = false;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgv.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.DisplayedCells;
            dgv.AllowUserToAddRows = false;

            dgv.SortStringChanged += (sender, e) => dgv_Dados_SortStringChanged(sender, e, bindingSource);
            dgv.FilterStringChanged += (sender, e) => dgv_Dados_FilterStringChanged(sender, e, bindingSource);
        }
```

Thanks in advance,

Kind regards

**Comment by davidegironi** [comment]
Hello,
That must be something related to your datatable, so to your elemento.Value

If you try building it with a sample datatable it works. I see you cast the Value to a DataTable, is it a DataTable?

Find below a test code that I've tested.

```
public void createDGV(AdvancedDataGridView dgv)
        {
            // sample datatable
            DataTable dataTable = new DataTable("test");
            dataTable.Columns.Add("col1", typeof(int));
            dataTable.Columns.Add("col2", typeof(string));

            dgv.Dock = DockStyle.Fill;

            BindingSource bindingSource = new BindingSource();
            bindingSource.DataSource = dataTable;
            dgv.DataSource = bindingSource;

            dgv.RowHeadersVisible = false;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgv.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.DisplayedCells;
            dgv.AllowUserToAddRows = false;
        }
```
        
I've try to replicate your

**Comment by rhandalfm** [comment]
Hello David, thanks so much for your answer! 

I work closely with Layla and continued digging into the issue as per your guidance.
I confirm to you that the Value is indeed exactly a DataTable.

So what I did was instead of inserting my DataTable, I created a new one at the same time and I kept having the same problem,

public void createDGV(KeyValuePair<string, object> elemento, AdvancedDataGridView dgv)
        {
            dgv.Dock = DockStyle.Fill;
            DataTable dt = new DataTable();
           
            DataTable dataTable = new DataTable("test");
            dataTable.Columns.Add("col1", typeof(int));
            dataTable.Columns.Add("col2", typeof(string));
            dt = dataTable;

            BindingSource bindingSource = new BindingSource();
            try
            {
                bindingSource.DataSource = dt;
                dgv.DataSource = bindingSource; // Here's the error
            }
            catch { }

            dgv.RowHeadersVisible = false;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            dgv.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.DisplayedCells;
            dgv.AllowUserToAddRows = false;

            dgv.SortStringChanged += (sender, e) => dgv_Dados_SortStringChanged(sender, e, bindingSource);
            dgv.FilterStringChanged += (sender, e) => dgv_Dados_FilterStringChanged(sender, e, bindingSource);
        }

I'm suspecting that the problem is in inserting several ADGV in different TabPages in the same TabControl.

As shown in the code below, for each report, I create a new ADGV and a new TabPage, and insert it into the existing TabControl.

foreach(var elemento in resultsList)
            {
                var tab = new TabPage();
                tab.Name = "tab_" + elemento.Key;
                tab.Text = elemento.Key;
                tab_Results.Controls.Add(tab);
                tab.Padding = new Padding(4, 4, 4, 4);
                tab.BackColor = Color.White;
                AdvancedDataGridView dgv = new AdvancedDataGridView();
                dgv.ReadOnly = true;
                tab.Controls.Add(dgv);
                createDGV(elemento, dgv);
            }

It would be really appreciated if you could help us one more time.

Kind regards

**Comment by davidegironi** [comment]
Hello @rhandalfm
I'm using several ADGV with no problem. Can you build a sample project?
