### ISSUE TITLE
Using ADGV with a list of objects

### ISSUE THREAD

**Issue by desarrollo03TR** [davidegironi/advanceddatagridview#11]
Can I use a List<T> as DataSource with BindingSource? Is there an example of using a List?

**Comment by davidegironi** [comment]
Hello, you should convert the list to a dataset, using something like the DGDataTableUtils you can find here https://gist.github.com/davidegironi/9348c74c01d979942901
Suppose you have the list myList of type MyListType (List<MyListType> myList) and you BindingSource myMainBindingSource, you can set the DataSource in this way myMainBindingSource.DataSource = DGDataTableUtils.ToDataTable<MyListType>(myList);
You can find an usage example here https://github.com/davidegironi/dguighf
