### ISSUE TITLE
Facing issue on filter string!

### ISSUE THREAD

**Issue by ehtasham-se** [davidegironi/advanceddatagridview#110]
Filter String unable to handle escape sequence value for string. Unable to filter date which contain "*", "\", "quote", "double quote" etc.

Please fixed it.

**Comment by davidegironi** [comment]
Hello @ehtasham-se 
Can you elaborate it? Which filter string do you mean? The one build up by the generator or the one of the checkbox list?

**Comment by ehtasham-se** [comment]
Hi @davidegironi 
When you select filter from grid, you will get FilterString and SortString on debugging. So if you filtering them which contain "*", "", "quote", "double quote", its not filtering properly. Because it change the format of string because of escape sequence.

**Comment by davidegironi** [comment]
Do you mean you are trying to filter columns of a Datatable which contain text values with asterisc or quotes?

**Comment by ehtasham-se** [comment]
yes

**Comment by davidegironi** [comment]
Let's take the sample project as example.
In AddTestData method, let's add some asterics to the "string" column
update the line from
`i*2 % 3 == 0 ? null : i.ToString()+" str",`
to
`i*2 % 3 == 0 ? null : i.ToString()+" str" + (i % 2 == 0 ? "*" : ""),`
now debug the program
I've no problem filtering the lines with asterisc
