### ISSUE TITLE
Filter records  based over the whole records when I use select top x

### ISSUE THREAD

**Issue by kmorales026** [davidegironi/advanceddatagridview#113]
Hi, I am using Advanced DataGridView to show almost 2000 record using Storage Procedure, I configured  Storage Procedure to show only the first 100 records, select top 100 * from table.

When I try to use filter function, its only show me the result based on the 100 records!!, but not over the whole records in the table!,

how can I do to show only the first 100 records, but when I use filter function it let me to filter based over the whole records?

**Comment by davidegironi** [comment]
Hello @kmorales026,
If I understand your needing, you want to show 100 rows in the table, but make the filter works on 2000 rows. It is something that could not be done, cause you are working on a single DataSet.
What i can suggest you is to add a custom column (let say "first 100"), customize the Filter for the DataSet to always set that column filtered (attaching the advancedDataGridView_main_FilterStringChanged event), and mark that column as not-visible. This could be a trick but you have to try.

**Comment by kmorales026** [comment]
Hi, I did it using the codes:
        private void DataGridGeneralMostrar()
        {
            try
            {
                DataTable tablaCompleta = NEnlaces.EnlacesMostrar();

                DataView dataView = tablaCompleta.DefaultView;
                dataView.RowFilter = ""; // Filtro inicial vacío para mostrar todos los registros
                dataView.Sort = ""; // Orden inicial vacío (opcional)

                DataTable primerosRegistros = dataView.ToTable().AsEnumerable().Take(30).CopyToDataTable();

                adgEnlaces.DataSource = primerosRegistros;
                this.dgGenerales();
                lblTotal.Text = "N° Registros: " + Convert.ToString(adgEnlaces.Rows.Count);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message + ex.StackTrace);
            }
        }

        private void adgEnlaces_FilterStringChanged(object sender, Zuby.ADGV.AdvancedDataGridView.FilterEventArgs e)
        {
            string filterText = adgEnlaces.FilterString;
            DataTable tablaCompleta = NEnlaces.EnlacesMostrar();
            DataView dataView = tablaCompleta.DefaultView;
            dataView.RowFilter = filterText;

            DataTable vistaFiltrada = dataView.ToTable().AsEnumerable().Take(200).CopyToDataTable();
            adgEnlaces.DataSource = vistaFiltrada;
            lblTotal.Text = "N° Registros: " + Convert.ToString(adgEnlaces.Rows.Count);
        }
        
DataGridView show many rows with the same name on column CUSTOMER, almost 2 different name, but if I have 5 o 7 name and datagridview only show 30 rows, when I use the filter it only filter based on data showed on datagridview and not from the table from SQL, it is posible to fix that? or ther is a documentation to do it?

**Comment by davidegironi** [comment]
You have to "play" with a couple of DataTable, one filtered, the other showed.
