### ISSUE TITLE
Filtering only shows selected values in the filter dialog

### ISSUE THREAD

**Issue by sraedler** [davidegironi/advanceddatagridview#116]
The first image shows the filter before selecting a value.
The second image shows that only the selected value is visible in the filter.

I would expect the unselected values to be displayed anyway.
Clearing the filter brings back all values.

What am I doing wrong?

<img width="152" alt="image" src="https://github.com/davidegironi/advanceddatagridview/assets/11181512/2896c705-8f3e-4e0a-a9d2-fa92a13961c4">

<img width="153" alt="image" src="https://github.com/davidegironi/advanceddatagridview/assets/11181512/da4532c8-fd13-41b1-83aa-9f589377dc78">

**Comment by AqibChattha** [comment]
Well, I don't think you can do that currently, but it sure looks like a nice feature to have. What do you think about this sir @davidegironi .

**Comment by sraedler** [comment]
Assuming that ADGV is the previous version of this project, this feature was already present.

See here: https://youtu.be/RaZeeHRRCGA?t=347

**Comment by davidegironi** [comment]
Hello,
you can use the SetChecklistTextFilterRemoveNodesOnSearchMode disabling the feture for a specific column.
If you look at the sample project you can find it disabled on the "decimal" column.
`advancedDataGridView_main.SetChecklistTextFilterRemoveNodesOnSearchMode(advancedDataGridView_main.Columns["decimal"], false);`
