### ISSUE TITLE
Setting FilterAndSortEnabled = false does not prevent changed cells being removed from collection

### ISSUE THREAD

**Issue by will-scc** [davidegironi/advanceddatagridview#119]
I'm not sure if this is a bug, but it's a behaviour I've found problematic. 

With a filter applied to a column (e.g. in the sample project the "boolean" column) which is set to only show certain values, e.g.:

![image](https://github.com/davidegironi/advanceddatagridview/assets/31592644/683ca898-aa2d-4864-91cb-08eee69a46b6)

If the value of display columns are changed, as soon as the cell/row is clicked off, it is removed from view, even when `FilterAndSortEnabled = false` is set.

I would expect no filtering actions to happen until `FilterAndSortEnabled = true` is set.

This is an issue because if you allow a user to select multiple cells/rows and change the values with a filter applied, every cell is removed one at a time and this triggers a whole bunch of `CellEnter` or `RowEnter` for events.

Adding this to the AdvancedDataGridViewSample project:

```c#
private void toggleBooleanToolStripMenuItem_Click(object sender, EventArgs e)
{
    advancedDataGridView_main.FilterAndSortEnabled = false;
    
    foreach (DataGridViewCell cell in advancedDataGridView_main.SelectedCells)
    {
        cell.Value = !(bool)cell.Value;
    }
    
    advancedDataGridView_main.FilterAndSortEnabled = true;
}

private void advancedDataGridView_main_CellEnter(object sender, DataGridViewCellEventArgs e)
{
    Debug.WriteLine("Cell " + e.RowIndex + " entered");
}
```

When you filter the `boolean` column to show either true or false, select a number of the cells, and call `toggleBooleanToolStripMenuItem_Click` you will see this sort of output:

```
Cell 3 entered
Cell 3 entered
Cell 2 entered
Cell 2 entered
Cell 1 entered
Cell 1 entered
Cell 0 entered
Cell 0 entered
Cell 0 entered
Cell 1 entered
Cell 1 entered
```

It would be a lot more efficient if it didn't remove the cells from view one at a time, instead would wait until `FilterAndSortEnabled = true` to remove in bulk.

I thought this change would solve it, but it doesn't:
```c#
protected override void OnCellValueChanged(DataGridViewCellEventArgs e)
{
    if (this.FilterAndSortEnabled)
    {
        if (e.RowIndex >= 0 && e.ColumnIndex >= 0)
            _filteredColumns.Remove(Columns[e.ColumnIndex].Name);
    }
    base.OnCellValueChanged(e);
}
```

**Comment by davidegironi** [comment]
Hello, are you talking about this behaviour? https://github.com/davidegironi/advanceddatagridview/issues/116

**Comment by will-scc** [comment]
> Hello, are you talking about this behaviour? #116

Nope. I would expect setting the `AdvancedDataGridView.FilterAndSortEnabled` property to false to disable filtering and sorting for the whole data grid, but when changing the values of a filtered column when this is set to false will still cause the rows to be removed from the grid view.

**Comment by davidegironi** [comment]
I still don't fully understaind. Can you share a sample project?

**Comment by will-scc** [comment]
> I still don't fully understand. Can you share a sample project?

Have a look at this fork: https://github.com/will-scc/advanceddatagridview/tree/master

I've added lines 418 onwards to `FormMain.cs` to hopefully demo the issue I'm having. Let me know if that helps, or if I can provide any further detail.

Also note, I had to update references to net40 to net48 to get it to build. If that causes you issues you should be able to change them back.

**Comment by davidegironi** [comment]
I'm still not sure about the behaviour you are searching for.
Could it be SetFilterAndSortEnabled on the column instead, like below?

```
private void toggleBooleanToolStripMenuItem_Click(object sender, EventArgs e)
{
            //after this, i would not expect see any filtering behaviour happening (i.e. rows removed from view)
            //advancedDataGridView_main.FilterAndSortEnabled = false;
            advancedDataGridView_main.SetFilterAndSortEnabled(advancedDataGridView_main.Columns["boolean"], false);

            foreach (DataGridViewCell cell in advancedDataGridView_main.SelectedCells)
            {
                if (cell.ColumnIndex == 6)
                {
                    //Swap cell value for demo
                    cell.Value = !(bool)cell.Value;
                }
            }

            //once this is set, filtering can happen again and now rows should disappear from view
            //advancedDataGridView_main.FilterAndSortEnabled = false;
            advancedDataGridView_main.SetFilterAndSortEnabled(advancedDataGridView_main.Columns["boolean"], true);
}
```

**Comment by will-scc** [comment]
Setting `AdvancedDataGridView.FilterAndSortEnabled = false` does not disable filtering and sorting on the data grid view... I'm not sure how else to say that. 😅

I tried `advancedDataGridView_main.SetFilterAndSortEnabled(advancedDataGridView_main.Columns["boolean"], false);` but doing so changes the SelectedCells property to a random cell (it seems), so it kinda breaks everything else.

**Comment by davidegironi** [comment]
The FilterAndSortEnabled field is supposed to work on component initialization, taking the AdvancedDataGridViewSample project as example, you can add this line at the end of the FormMain costructor
`advancedDataGridView_main.FilterAndSortEnabled = false;`

The SetFilterAndSortEnabled method works after the columns has been added too. Of course it change the underlying datasource Filter, so the selected cell changes, you have to record the selected cell, and set it back again.
