### ISSUE TITLE
Search box 

### ISSUE THREAD

**Issue by frahman2** [davidegironi/advanceddatagridview#12]
Hi,

I am using your ADV, and I have to say that it's great, however in the previous releases there was a search text box in the Columns filter. Please is there a way to have it back. 
![missing_adgv](https://user-images.githubusercontent.com/22269776/27818020-f6f9317c-60a4-11e7-8036-1f68b4cea7a2.JPG)

**Comment by davidegironi** [comment]
Hello and thank you. In my release there has never been that search box, I suppose you are talking about another release, anyway it could be an interesing implementation. Let me know if you are planning to build that.

**Comment by frahman2** [comment]
Hi,
I had one of your old releases which contained that, any how I have Added it to the the new release. I have built it and it' working fine.  
![adgv](https://user-images.githubusercontent.com/22269776/27896528-c343e5a6-622b-11e7-8473-79a383bb0bff.png)

**Comment by frahman2** [comment]
Attached after Building

[AdvancedDataGridView.zip](https://github.com/davidegironi/advanceddatagridview/files/1126810/AdvancedDataGridView.zip)

**Comment by WinProgrammer** [comment]
An easier way frahman2 instead of a zip file, would be to create a fork of the project, then you can do a Pull Request of your changes. Makes it much easier for fork maintainers to check other people's updates, fixes etc.

Just some constructive criticism :)

**Comment by frahman2** [comment]
Thank you for the comment :+1:  , I will keep than in mind.

**Comment by davidegironi** [comment]
Than you frehman2.. give me some days to inspect the code then i will try the merging

**Comment by davidegironi** [comment]
Hello, try out this version, available for 2 days: https://expirebox.com/download/3f7439f3039ce14ee431b9be06dd4486.html
Let me know, if you think the behaviour is correct I will publish that.

**Comment by frahman2** [comment]
Hi David,

it's working fine, however it's slower and is providing the option to select based on the search criteria, I would rather go for the same behavior of excel to filter the list and show only the queried data. Please see below screen shot for the last version uploaded by you.
![adgv-search02](https://user-images.githubusercontent.com/22269776/28009174-849748e6-656b-11e7-9f39-734fd224aafd.png)

Please see below screen shot of shape of what do I mean, Please you can find the Built code 
[https://github.com/davidegironi/advanceddatagridview/files/1126810/AdvancedDataGridView.zip](url)

![adgv-search-01](https://user-images.githubusercontent.com/22269776/28009186-90aaccc0-656b-11e7-8ebd-59eadd96cfdd.png)

**Comment by davidegironi** [comment]
Hello, I do not understand what you mean with "slow", to me it seems the same speed, anyway, here you can find the code with the Excel behaviour implemented, one can even build his version with that behaviour not implemented imposing to false _checkTextFilterRemoveNodesOnSearch from MenuStrip.cs.
Code here (2 days expire): https://expirebox.com/download/11e36dca6335aae873455a85f25b5617.html
This also implements a Fix in the double filter.

**Comment by frahman2** [comment]
Hello, I meant By slow based on amount of data ( More than 80,000 records ). Please the link is expired, as I am interested to see the fix of the double filter.
Thank you.

**Comment by davidegironi** [comment]
Hello, here it is the new link: https://expirebox.com/download/4bdab5640f4714f32a7034ac5feb657d.html

**Comment by frahman2** [comment]
Great and well done.
Thanks

**Comment by davidegironi** [comment]
Thank you. Can you provide a sample code for that. Maybe starting from the actual github version, which I've updated right now.

**Comment by davidegironi** [comment]
Hello @frahman2 I close this issue. I can not repeat the "open/close form" error, please open a new issue with sample code from the last stable release.

**Comment by frahman2** [comment]
Thank you so much

**Comment by davidegironi** [comment]
@frahman2 There was a little issue in the actual Excel like version, opening the box after the filter is set I prefer to have the complete checked/unchecked. This version here implements this behavior (2 days expires): https://expirebox.com/download/8910f06f71fd9288f83b65700d4ee388.html
Let me know what do you thing about that. Thank you.

**Comment by frahman2** [comment]
Hi, 
Davide I am sorry I was Away for couple of days, Please re upload again.

Regards,
Firas

**Comment by davidegironi** [comment]
Hello, no problem, here is the new link: https://expirebox.com/download/1be082a49f1288333a6ec1ea840d6eea.html

**Comment by frahman2** [comment]
Great and the performance is good.

**Comment by davidegironi** [comment]
@frahman2 Thank you for testing. I will close this issue now and publish a release. Again, I can not repeat the "open/close form" error, please open a new issue with sample code from the last stable release.
