### ISSUE TITLE
how to speed up filter menu in adgv?

### ISSUE THREAD

**Issue by farshadvl** [davidegironi/advanceddatagridview#120]
HI man .
I have a data table with more than 170.000 record and 40-50 columns.
when I bind my dt to adgv it works but when I want to filter each column it hangs about 10-12 second and after that it works fine.
how can I handle this situation?
How can I make this filter menu speed faster?

**Comment by davidegironi** [comment]
Hello,

this component is not optimized for that amount of data. You may try to take a look at the MenuStrip code, whre the load of the objects happens. I've to investigate it further but I think this could be an hard task.
Consider that even Excel has a filter limit of 10000 values. I still prefer not to limit this in code.
As best practice to my experience more than 2000 rows per view are yet difficult to manage for the human operator, so I sugget you to pre-filter the binded DataSet, then load it to the DataGridView you are using.
