### ISSUE TITLE
AdvancedDatagridView - 1.2.28405.11 - Problem when clicking on filter / search drop down

### ISSUE THREAD

**Issue by MattH-Work** [davidegironi/advanceddatagridview#121]
Is there any know reason why, when i click on the filter / search drop down, 
![image](https://github.com/davidegironi/advanceddatagridview/assets/84494183/cf1a2c98-9629-4793-b301-41881ac2bc3c)
the resulting menu flashes then disappears

Only happens with 1 datagrid, all the other work as expected

**Comment by davidegironi** [comment]
Hello,
I can not reproduce this issue.
Do you mean the first(1) column or the first(1) datagrid of your project?
Which is your .NET version?
Can you check if it happens on the sample project of this source code?

**Comment by MattH-Work** [comment]
Issue resolved 'itself' !
