### ISSUE TITLE
How to use Advanced DataGridView Search Tool Bar

### ISSUE THREAD

**Issue by cadmonkey123** [davidegironi/advanceddatagridview#123]
hi I saw the same post but I can't find an example in the example project. Could you post here the need event(s) and examples to get these functions working, thanks. I have added the column's to the search bar 
AdvancedDataGridViewSearchToolBar1.SetColumns(AdvancedDataGridView1.Columns)

**Comment by davidegironi** [comment]
Hello, you can find and example in the sample project.
