### ISSUE TITLE
filter button_click events

### ISSUE THREAD

**Issue by rezarahimy** [davidegironi/advanceddatagridview#125]
I want after the select item in combo and click Filter button immediately calculate sum of one column value

**Comment by davidegironi** [comment]
Hello,

if you mean having a raw with the total value, you have to post/compute that, and add to the dataset. The feature you are asking is not part of advanced data grid view.

**Comment by rezarahimy** [comment]
Hello, thank you very much for your reply
I want to have the sum of column 9 after filtering column 2
  At the same time as clicking the filter button, the sum event is done and
I don't have to define a new button and click for sum
Best Regards



Public Class Form1
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles
Button1.Click
        Try

SpGetHotelRevenueTableAdapter.Fill(Lotus_foDataSet.spGetHotelRevenue,
MaskedTextBox1.Text, MaskedTextBox2.Text)
            TextBox1.Text = AdvancedDataGridView1.RowCount
        Catch ex As System.Exception
            System.Windows.Forms.MessageBox.Show(ex.Message)
        End Try
    End Sub
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
 this sub not work
    Private Sub AdvancedDataGridView1_FilterStringChanged(sender As Object,
e As Zuby.ADGV.AdvancedDataGridView.FilterEventArgs) Handles
AdvancedDataGridView1.FilterStringChanged
        TextBox1.Text =
AdvancedDataGridView1.Rows.GetRowCount(DataGridViewElementStates.Visible)
        TextBox2.Text = FormatNumber((From row As DataGridViewRow In
AdvancedDataGridView1.Rows.Cast(Of DataGridViewRow)() Select
CDec(row.Cells(9).Value)).Sum, 0)
    End Sub
    'this sub not work
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
   Private Sub Button2_Click(sender As Object, e As EventArgs) Handles
Button2.Click
        TextBox1.Text =
AdvancedDataGridView1.Rows.GetRowCount(DataGridViewElementStates.Visible)
        TextBox2.Text = FormatNumber((From row As DataGridViewRow In
AdvancedDataGridView1.Rows.Cast(Of DataGridViewRow)() Select
CDec(row.Cells(9).Value)).Sum, 0)

    End Sub

End Class

**Comment by davidegironi** [comment]
It's something out of the advanceddatagridview context. That is functional code you have to write in your own application.
I would add an event to the underling bindingsource (ListChanged), rather than filterstrinchanged, anyway that's up to you.

**Comment by rezarahimy** [comment]
Thanks for the tip!
