### ISSUE TITLE
Verticle Scroll Bars Disappear

### ISSUE THREAD

**Issue by markhembree66** [davidegironi/advanceddatagridview#126]
I ran across an oddity with the scroll bars in the advanced datagridview. Whenever the form is resized, the vertical scroll bar goes away. It happens no matter how many records are being displayed. The horizontal scroll bar acts properly during the form resize. I even tried to force the scroll bars to be shown by placing “advancedDataGridView1.ScrollBars = ScrollBars.Both;” in all of the resize events.

This makes it very difficult for the user to be able to insert new rows into the table. Any ideas?

**Comment by markhembree66** [comment]
One additional comment - this only happens when a "datetime" field is defined in the datatable used in the data source.

**Comment by davidegironi** [comment]
Well done @markhembree66.
Just as a note: as your email the issue was not related to the advanced datagrid view.
