### ISSUE TITLE
Filter Support On Toolbar

### ISSUE THREAD

**Issue by JWPlatt** [davidegironi/advanceddatagridview#127]
I'd like to see a filter mode added to the search toolbar.  Add a "Mode" dropdown with "Search" and "Filter".  Filter mode would highlight the search word as usual plus not display any rows without the word.

**Comment by davidegironi** [comment]
Hello JWPlatt,
as you can see in the sample project the search toolbar it's based on events.
It can be implemented some custom code that makes the search toolbars works in filter mode, like you need. You can as example build up a filter string and filter the underline dataset. But that's out of the scope of the Search toolbar.
If you are going to implement something please share your code here.

**Comment by JWPlatt** [comment]
VS 2019 and 2022 still do not support Visual Inheritance.  I'm trying to figure out how to make it open AdvancedDataGridViewSearchToolBar.cs in the designer to work on it.  It opens the code, but not the Designer.  I don't want to directly edit AdvancedDataGridViewSearchToolBar.designer.cs.  How do you get it in the Designer?

Also, is it okay to upgrade this to VS 2022?

**Comment by JWPlatt** [comment]
Hi,

Can you answer above questions?

Thanks.

**Comment by davidegironi** [comment]
Hello,
I've done it without the designer. It's in the .designer.cs file
Yes you can use VS 2022.
