### ISSUE TITLE
Going further with even more advanced flexibel filters

### ISSUE THREAD

**Issue by LightTempler** [davidegironi/advanceddatagridview#13]
Hello,
first of all: Great to see development of this control is going on, many thanks for!

I'm looking for possibilities to take filtering to an very user orientated level. In combination with saving filters this could save so many time, if you need same filters of updated data on regular base.
A good example is checking a logfile for three different complex combined filters/sorts. 

**Date**   Descriptive time ranges like 'last 4 hours', 'today', 'last two days', 'this week', 'this month', ...

**String**   Collections with OR connected expressions like {'Starts with Error*"' OR 'Contains "*warning*"' OR 'Ends with "*expired"}

**Interger**  Collections of OR connected expression like {'= 0' OR 'Between 10 and 20' OR 'Less than 100'}

Ok, thats more than a missing . in a comment ;-)
But maybe possible to add in an upcomming release ...

Thank you for reading my suggestion.
LiTe

**Comment by davidegironi** [comment]
@LightTempler hello and thank you.

For the **String** you can use the _Custom Filter_, you can find there equals, begin with.. and so on
About the **Integer** and **Date** request, this will be an interesting features to add. At present I'm involved in other project, but when I had time I will thing about adding that. In the meanwhile if you plan to implement those features please share that here.

Thank you,
Davide

**Comment by LightTempler** [comment]
I understand 'Custom Filters' for strings and the options there. What I miss/need are MORE than one of the wildcard conditons there OR connected: This OR this OR this.

**Comment by davidegironi** [comment]
@LightTempler now i get that. When i had time that would be an interesting feature to implement.

**Comment by LightTempler** [comment]
Sounds great, thank you!
Hint: Waste no time in trying to get requests like (IN ('Begin%', '%middle%, '%endhere')) to work. I 've already tried your demo code and goggled up and down: IN doesn't work with wildcards :(
But an extended filter dialog with let 's say three conditions and a WHERE LIKE 'Begin%' OR WHERE LIKE ... would fit most needs/cases.

**Comment by davidegironi** [comment]
@LightTempler thank you for your feedback. I have to admin that now I'm really fully involved in other things and I do not know when I could do that, but anyway, you will eventually see this update right here.
