### ISSUE TITLE
Query - Is this possible?

### ISSUE THREAD

**Issue by MattH-Work** [davidegironi/advanceddatagridview#132]
Notice in the attached screenshot, that the columns are 'stacked' to allow more info to be displayed within a finite width of datagrid.
Is something like this possible using AdvancedDatagridView?

![image](https://github.com/davidegironi/advanceddatagridview/assets/84494183/42e3b14b-dc40-4c52-a43f-61a625111bd0)

**Comment by davidegironi** [comment]
Hello,
It's not possible.

**Comment by davidegironi** [comment]
I take the opportunity to ask you if have you have been able to check my last issue solution proposed here: https://github.com/davidegironi/advanceddatagridview/issues/131

**Comment by MattH-Work** [comment]
I havent had the chance to check, but I do appreciate the work you have done

Matt

**Comment by davidegironi** [comment]
Thanks!
