### ISSUE TITLE
Filter DatagridViewImageColumn

### ISSUE THREAD

**Issue by ivanbsa75** [davidegironi/advanceddatagridview#137]
Hi Davide,
using your .Nuget components and trying to filter a column defined as ImageColumn an error occurs. See image attached.

Can you please tell me if the problem is solvable or i can use a property to disable filter in this column?
![Image](https://github.com/davidegironi/advanceddatagridview/assets/171336918/06e58bf3-46c8-4f17-ba5e-6509c7b26cd9)

Thanks in advance,

Best Regards

Ivan

**Comment by davidegironi** [comment]
Hello, you can take a look at the sample project. There you can find a sample of an image column.

**Comment by ivanbsa75** [comment]
Thanks a lot !!

Best regards

Ivan

Il giorno ven 31 mag 2024 alle ore 14:14 Davide Gironi <
***@***.***> ha scritto:
