### ISSUE TITLE
How to reference AdvancedDataGridView in VB.NET that uses .NET 6.0

### ISSUE THREAD

**Issue by GaryHagerty** [davidegironi/advanceddatagridview#138]
Hello,

I have used your AdvancedDataGridView in a Visual Studio 2015 project using .Net Framework with no problem. Now I am porting over to .NET 6.0 VS2022 and downloaded the latest AdvancedDataGridView .NET 5.0 version.

I add a reference to the  AdvancedDataGridView.dll, but it does not show on in the toolbox.

Please tell me what I am doing wrong

Thank you

Gary

**Comment by davidegironi** [comment]
Hello,
I've checked it. On a sample project I've made it works.
Simply use the nuget packet manager to add this reference. https://www.nuget.org/packages/DG.AdvancedDataGridView

![Capture](https://github.com/davidegironi/advanceddatagridview/assets/1426098/b2e78507-d785-4eeb-a4e5-d4057cec09e2)
