### ISSUE TITLE
Support for High DPI

### ISSUE THREAD

**Issue by nhinzevt** [davidegironi/advanceddatagridview#14]
Thanks for this awesome control. I'm having trouble upgrading it to work for High DPI screens. I updated the ADV Sample code using the link below. Everything looks sharp, but the filter is having some formatting problems.

<img width="627" alt="capture" src="https://user-images.githubusercontent.com/16492026/29986239-8c16bbc6-8f30-11e7-9a79-b275109bb0ae.PNG">

http://crsouza.com/2015/04/13/how-to-fix-blurry-windows-forms-windows-in-high-dpi-settings/

**Comment by davidegironi** [comment]
Hello and thank you. I think you have to check the private void ResizeBox method in MenuStrip.cs. Please do it with a parametric option, so one can enable or disable the High DPI capabilities. If you do that please let us know.

**Comment by nhinzevt** [comment]
I have started work on this in my fork. From my testing, a parametric option is not needed so far, because on normal DPI the scaling is 1.0.

I'm having trouble removing or hiding the black triangular arrows. I don't understand where they are coming from:

<img width="238" alt="capture" src="https://user-images.githubusercontent.com/16492026/30109781-a144fa6e-92d5-11e7-98f5-a90a6de9a63d.PNG">

Work In Progress branch:

https://github.com/nhinzevt/advanceddatagridview/tree/handle-high-dpi

**Comment by davidegironi** [comment]
I've download your branch and compile, but I don't have that triangles coming out. I must say that do not have an High DPI monitor so it may depends on that.

**Comment by davidegironi** [comment]
@nhinzevt  I was solving the issue here and I maybe found a way to make it woks with High DPI.
Thank you for your feedback.
Try this version out: https://expirebox.com/download/ad438cc44617404073d785f1f0888f25.html
Expires in 2 days.
Let me know. You have to try because i do not have any High DPI to test it against, thank you.

**Comment by nhinzevt** [comment]
I used the following file in the download:

\AdvancedDataGridView\AdvancedDataGridView\bin\Release\AdvancedDataGridView.dll

The result appears to be the same:

<img width="214" alt="adgv" src="https://user-images.githubusercontent.com/16492026/30395886-b4f5a8fe-9895-11e7-986c-90f78e92b6cf.PNG">

**Comment by davidegironi** [comment]
Thank you for your test. It is still something related to ResizeBox method in MenuStrip.cs but I do not know how to fix it. If you find a solution please post it here.
