### ISSUE TITLE
Sort/Filter only showing values for first column.

### ISSUE THREAD

**Issue by PahrensMlx** [davidegironi/advanceddatagridview#140]
I'm having an issue where no matter which column I click on, it only shows the values for the first column under the list of available filters.

![image](https://github.com/user-attachments/assets/549738ec-6d0e-4552-8408-4ea7870cbe1b)

If I click on another column later, it doesn't show anything.  It will only show values for the first column.
![image](https://github.com/user-attachments/assets/eb606405-a4c0-4a66-b807-da0f21c5c65c)

If I try to apply one of these filters, it does not work.  This is in a project that had been working previously.  I made some changes to allow the user to edit values, where it was read only before.  I also had to do some work to how it loads column data to create combobox and checkbox columns for certain fields.  It seems like it is lacking information about the columns, so assuming that's where the issue is, but I'm not sure what it would be missing or how to fix it.

Any help or ideas would be greatly appreciated.

**Comment by PahrensMlx** [comment]
I've been able to narrow it down to this area of code, which is the section that does those column modifications.

`            dgvResults.Columns.Clear()
            For I = 0 To tmpData.Columns.Count - 1
                Dim Column As DataColumn = tmpData.Columns(I)
                Dim tmpColumn As New DataGridViewColumn

                Select Case FormData.Fields(I).ColumnType
                    Case 0  'Let Automatic decision based on data type.
                        Select Case Column.DataType.Name
                            Case "Boolean"
                                tmpColumn = New DataGridViewCheckBoxColumn
                            Case Else
                                tmpColumn = New DataGridViewTextBoxColumn
                        End Select
                    Case 1
                        tmpColumn = New DataGridViewTextBoxColumn
                    Case 2
                        'combo boxes require a little extra setup.
                        Dim _cbxColumn As New DataGridViewComboBoxColumn
                        '_cbxColumn.Items.AddRange(FormData.Fields(I).ComboBoxColumnItems)

                        Dim ComboBoxData As clsField.ComboBoxItemsEventArgs = FormData.Fields(I).RaiseEvent_GetComboBoxItems(FormData)

                        _cbxColumn.DataSource = ComboBoxData.ColumnItems
                        _cbxColumn.ValueMember = ComboBoxData.DataMember
                        _cbxColumn.DisplayMember = ComboBoxData.DisplayMember
                        tmpColumn = _cbxColumn
                End Select

                tmpColumn.DataPropertyName = Column.ColumnName
                dgvResults.Columns.Add(tmpColumn)
            Next`

**Comment by davidegironi** [comment]
Hello,
Sorry but I can not understand the problem you have. Maybe it is related to your underline DataSource. Can you reproduce it to the using the Sample project in this github solution?
