### ISSUE TITLE
advanceddatagridview ru localization

### ISSUE THREAD

**Issue by MaMuH-6orATblPb** [davidegironi/advanceddatagridview#142]
Hello!
Tell me please, how to enable Russian localization?
Thank you!
![42962898-62f77a1a-8b9b-11e8-98bf-3e89075880ce](https://github.com/user-attachments/assets/f771a8c4-1e94-4042-9593-d09bd61f48a9)
Например, эти элементы. Сортировка по алфавиту, фильтр, отмена, очистка сортировки и так далее. Они на английском языке.

**Comment by davidegironi** [comment]
Hello, find the sample code in the sample project.
Basically you could load it from file by using the method:
`AdvancedDataGridView.SetTranslations(AdvancedDataGridView.LoadTranslationsFromFile("your-russian-lang.json"));`

**Comment by MaMuH-6orATblPb** [comment]
а куда этот код вводить?

**Comment by MaMuH-6orATblPb** [comment]
where should I enter this code?

**Comment by MaMuH-6orATblPb** [comment]
all figured out, thank you!
