### ISSUE TITLE
Hi! Can you tell me how to change the icons in the filter? Thanks!

### ISSUE THREAD

**Issue by MaMuH-6orATblPb** [davidegironi/advanceddatagridview#143]
![2024-10-19_21-23-39](https://github.com/user-attachments/assets/75bc09d4-82ce-4478-ba7f-1f4ec9e817b6)

**Comment by MaMuH-6orATblPb** [comment]
to the left of sort A to Z

**Comment by davidegironi** [comment]
You have to recompile it. Those icons are hard compiled. You can find it in the Resources folder of this project.
