### ISSUE TITLE
I want to Filter DataGridview without DataSource

### ISSUE THREAD

**Issue by bhagvatdave** [davidegironi/advanceddatagridview#146]
I want to Filter DataGridview without DataSource

I am adding Columns in DataGridview manually in winform designer and after that while form loading i am adding data row by row and after i am filtering data but in filterstring column name is missing so it throw error so what is the problem

**Comment by davidegironi** [comment]
Hello @bhagvatdave 
Take a look here: https://github.com/davidegironi/advanceddatagridview/issues/24
