### ISSUE TITLE
How to make a column in filter mode at the beginning

### ISSUE THREAD

**Issue by Bakbak001** [davidegironi/advanceddatagridview#148]
Thanks for your hard work 👍 

if i have column called names and items are : mike, john, mody, frank, ahmed, sarah

and when the user run the project the default filter value is john

how to make this?

**Comment by davidegironi** [comment]
You can only set the filterstring, otherwise you could use the trick of pre-filtering the datasource, and loading the full source when it's modified. But in this case you will not see all the filtering option

**Comment by Bakbak001** [comment]
Thanks .. i Hope you make it in the future :)

**Comment by davidegironi** [comment]
Hope to have that time too :)
