### ISSUE TITLE
the language from lang.json not loaded at startup

### ISSUE THREAD

**Issue by Bakbak001** [davidegironi/advanceddatagridview#149]
Hi [davidegironi](https://github.com/davidegironi)

according to this problem 

[I want to change language to arabic and the form direction #145](https://github.com/davidegironi/advanceddatagridview/issues/145) 

I attached a video that show the problem

https://github.com/user-attachments/assets/65d1000e-98df-4685-881e-49202cb1dfd2

at the first load of advanced datagrd view (in usercontrol) the language still english , but if i go to another usercontrol and return ( or i reload the same usercontrol ) it turns to arabic

i want it to be Arabic from the beginning

**Comment by davidegironi** [comment]
Issue already discussed here https://github.com/davidegironi/advanceddatagridview/issues/145

**Comment by Bakbak001** [comment]
I know , i am the same person :)

you can watch the video

the problem is the language not run at the start , i have to go to another usercontrol to load the language

**Comment by davidegironi** [comment]
I know you are the same person. Do not open double issue for the same thing please.

**Comment by Bakbak001** [comment]
I am sorry, I thought the last issue was closed and you will not see it again

**Comment by davidegironi** [comment]
No problem. I always try to read post, even on closed one.

**Comment by Bakbak001** [comment]
What do you think about that issue ?

**Comment by davidegironi** [comment]
Find my comment here: https://github.com/davidegironi/advanceddatagridview/issues/145#issuecomment-2491851890
Please keep writing on the original issue
