### ISSUE TITLE
Risizing filter dialog

### ISSUE THREAD

**Issue by LightTempler** [davidegironi/advanceddatagridview#15]
Hello,
after resizing (increasing) a filter dialog, the size grip right bottom vanishes and you cannot resize this filter dialog anymore. Dialog looks different diesigned after resizing.
Behavior persists on reopening and belongs to just the selected column.

Regards
LiTe

**Comment by davidegironi** [comment]
Thank you for your feedback.
Try this version out: https://expirebox.com/download/ad438cc44617404073d785f1f0888f25.html
Expires in 2 days.
That bug should be fixed. Let me know.

**Comment by LightTempler** [comment]
You are fast :)
Thanks alot, this one is fine!
Now size grip is still visible after releasing mouse button.

**Comment by davidegironi** [comment]
Thank you @LightTempler  for you feedback.
I'm waiting for the @nhinzevt one from this issue https://github.com/davidegironi/advanceddatagridview/issues/14 then I will push the new version.

**Comment by davidegironi** [comment]
I've updated the source and release right now.
