### ISSUE TITLE
Drop Down Filter, change default behaviour

### ISSUE THREAD

**Issue by MattH-Work** [davidegironi/advanceddatagridview#151]
Is there a mechanism for the Filter Textbox to be focused by default when we drop the filter/sort button?
I usually type my filter string, but I always forget to 'activate' the search textbox before typing

Cheers

![image](https://github.com/user-attachments/assets/4ded6e68-d985-4755-97ff-46d10b174ceb)

**Comment by davidegironi** [comment]
Hello,

try the version below. Let me know if it works.
I've added a function to enable or disable this feature. It's SetFilterTextFocusOnShow
Default disabled, notice it on the Sample project advancedDataGridView_main.SetFilterTextFocusOnShow(true);

[advanceddatagridview-master.zip](https://github.com/user-attachments/files/18125579/advanceddatagridview-master.zip)

**Comment by MattH-Work** [comment]
Cheers, works like a charm!

**Comment by davidegironi** [comment]
released to nuget and to master branch
