### ISSUE TITLE
Saved Filter Query

### ISSUE THREAD

**Issue by MattH-Work** [davidegironi/advanceddatagridview#152]
Filter strings are saved in the following format

([Date] > '2024-12-09 00:00:00') AND ([Delegate_Qty] < 6)

( the date was set via a customer filter )
![image](https://github.com/user-attachments/assets/22d07864-c9cd-4807-89bd-e5f7e3899b59)

How would I reformat the string so that the Date is ALWAYS later than today, regardless of today's date
I tried ([Date] > '**_NOW_**') AND ([Delegate_Qty] < 6) but get an error
![image](https://github.com/user-attachments/assets/e7d6eabc-cea0-4026-a630-fe4aa56098c5)

**Comment by davidegironi** [comment]
You can not.
You should use a trick like replacing it in a string, then use this string as filter, something like below:
```
String myfilter = "([Date] > '_TODAY_') AND ([Delegate_Qty] < 6)";
myfilter = myfilter.Replace("_TODAY_", DateTime.Now.ToString("yyyy-MM-dd 00:00:00"));
```

**Comment by MattH-Work** [comment]
Davide,

Thanks for the response, 
Your suggestion is exactly what I am currently doing.
It just means I have to pre-build the filter string, rather than allowing the end user to create 'future' date filters on the fly & save them
