### ISSUE TITLE
Queston about usage of TriggerFilterStringChanged

### ISSUE THREAD

**Issue by MattH-Work** [davidegironi/advanceddatagridview#153]
In an attempt to stop 'LoadFilterAndSort' from locking up the columns headers ( see #59 ) I see we can use TriggerFilterStringChanged

I am struggling to see how to implement this

Can you give me a quick rundown on the process?

I have a saved Filter String, where do I pass this to the ADGV so that the filter is applied but without locking the columns
My saved filter string deals with multiple columns
I see that the following code will apply a saved filter to a single column '**_string_**'

Private Sub advancedDataGridView_main_FilterStringChanged(ByVal sender As Object, ByVal e As Zuby.ADGV.AdvancedDataGridView.FilterEventArgs)
    Dim stringcolumnfilter As String = textBox_strfilter.Text
    If Not String.IsNullOrEmpty(stringcolumnfilter) Then e.FilterString += (If(Not String.IsNullOrEmpty(e.FilterString), " AND ", "")) & String.Format("**_string_** LIKE '%{0}%'", stringcolumnfilter.Replace("'", "''"))
    textBox_filter.Text = e.FilterString
End Sub

**Comment by davidegironi** [comment]
Hello,
the LoadFilterAndSort lock all up cause it "force" the filter and sort as a string, but it does not inject the state of the filter and sort objects. So one does not know how that specific columns state was. Recording the state of each column needs a rewrite of some core side of the project, and this is something I've not time to do now.
I strongly suggest not to de-lock the column, cause you will have an inconsistent state in comparison with your string filter and sort.
Hope this clarify your doubt.
