### ISSUE TITLE
Can I disable checklist?

### ISSUE THREAD

**Issue by seiyata** [davidegironi/advanceddatagridview#17]
Could you advise how to disable the checklist of values when the button on column header clicked?
The checklist is useful but OutOfMemory error happens when handing huge number of records (> 500,000).

Btw, thank you very much for this very helpful tool :)

**Comment by davidegironi** [comment]
Hello, you could edit the MenuStrip.cs file in order to add a disabler for the list. If you do this by parameters and methods, please share the code here.

**Comment by davidegironi** [comment]
Addendum: I've just added the enabled for checklist try this version here and let me know https://expirebox.com/download/e1f4f9be00ee7ec79ceea3692b50cfb2.html link expires in 2 days.

**Comment by seiyata** [comment]
The change worked great, thanks!
Can we hide the checklist area itself when the function disabled just for better looking?

![2018-01-18_10h48_28](https://user-images.githubusercontent.com/3234960/35076798-85bf6672-fc3d-11e7-9114-81bd6cfb6915.png)

**Comment by davidegironi** [comment]
Yes, you have to code a little it in the MenuStrip.cs file, look at the sizing function.

**Comment by seiyata** [comment]
Sure, I'll try. Thanks.
