### ISSUE TITLE
Nuget pack

### ISSUE THREAD

**Issue by linefinc** [davidegironi/advanceddatagridview#18]
The work is remarkable but on Nuget store there's the old package.

It's possible to publish the current state of art?

Best regard

**Comment by davidegironi** [comment]
Published to nuget https://www.nuget.org/packages/DG.AdvancedDataGridView/

**Comment by linefinc** [comment]
Davide, 

if you want, you can use https://ci.appveyor.com/ to build, validate and auto publish the code

**Comment by davidegironi** [comment]
Thank you for suggestion!

**Comment by linefinc** [comment]
Sorry, I forgot , the service it's free for Open Source project
