### ISSUE TITLE
I was using nuget version (ADGV) and can't upgrade it to new one

### ISSUE THREAD

**Issue by tlgcmn** [davidegironi/advanceddatagridview#19]
Can you give some information about updating stable published release from nuget.
I download your new files and add as project reference but couldn't be able to work with them.

**Comment by davidegironi** [comment]
Hello,
This is not the ADGV by Zuby, this is a fork of a the Zuby project.
If you are using Zuby library here: https://www.nuget.org/packages/ADGV/
You have to change slighly your code to make this library run.
To test this library you can use the sample project provided
So, just
git clone https://github.com/davidegironi/advanceddatagridview
delete the AdvancedDataGridView project
remove the AdvancedDataGridView reference on the AdvancedDataGridViewSample project
on the sample project add the nuget reference of DG.AdvancedDataGridView
