### ISSUE TITLE
Advanced  Datagrid View - Visual Basic

### ISSUE THREAD

**Issue by jpmarques1** [davidegironi/advanceddatagridview#20]
Hello,

I'm trying to use ADVG with Visual Basic.

So far I'm doing fine for the basic functions and I'm really happy that ADVG is a consistent project.

Q1: How can i programatically change the sort icon from Ascending to Descending?

I would appreciate it very much if you could share some visual basic examples.
Thanks very much

**Comment by davidegironi** [comment]
Hello,

to sort columns you just have to use the SortASC and SortDESC method, something like this:
`advancedDataGridView_main.SortASC(advancedDataGridView_main.Columns["double"]);`

Unluckly I do not have vb.NET examples.
