### ISSUE TITLE
Clean sort of one column

### ISSUE THREAD

**Issue by jpmarques1** [davidegironi/advanceddatagridview#21]
Hello,

I've a DGV with 7 columns and a sortstring with multicriteria.

How can I programatically clean the sort of only one column.

Thanks in advance,
JM

**Comment by davidegironi** [comment]
Hello,

there not method to clean just one column Sort, you can use CleanSort method to clean all the column sort.
If you are going to implement the CleanSort and CleanFilter and CleanFilterAndSort to one column, please share this with us. Thank you!
