### ISSUE TITLE
Set Filter String Programatically

### ISSUE THREAD

**Issue by jpmarques1** [davidegironi/advanceddatagridview#22]
Hello,

I've two forms.

Main form with some buttons and combos and one form with an ADGV.

How can I open the form with the ADGV and programatically set the filter for two columns according to the selections of the main form

Thanks in advance,
JM

**Comment by davidegironi** [comment]
Hello,

you can pass parameter to the constructor of the WinForm you are opening, then use the parameter you pass to set the sort (SortASC and SortDESC method), let's say OnLoad event on the Form.

**Comment by jpmarques1** [comment]
Hi David,

Thanks for your quick answer.

I need to pass to the new form the filter not the sort. Is there method for controlling the filtering for each column?

Thanks i nadvance,
JM

**Comment by davidegironi** [comment]
Hello @jpmarques1, I'm sorry i though you are asking the same question as yesterday.
Anyway, unluckly there is no way at present to do this.
I may implement that in a future release, but nowaday I don't have time to develop on this project.
Of course, if you are going to implement this feature please share it here.
