### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by macgyver76** [davidegironi/advanceddatagridview#28]
Can you add some ILocalizationProvider or resource file to setup custom context menu texts?

**Comment by davidegironi** [comment]
Hello @macgyver76 , it's not in the upcoming plans, it would not be that difficult. I'll try to find time in the next days to do this but I can not promise it cause it's a pretty full period, sorry about that. I'll let you know.

**Comment by davidegironi** [comment]
Hello @macgyver76 , can you please check this out? (this file will expire)
https://file.io/rO2Xxp
Tell me if it's good and if it works for you.
The sample files contains all the things you need in order to set it up.
Partial translations are admitted.

**Comment by macgyver76** [comment]
> Hello @macgyver76 , can you please check this out? (this file will expire)
> https://file.io/rO2Xxp
> Tell me if it's good and if it works for you.
> The sample files contains all the things you need in order to set it up.
> Partial translations are admitted.

@davidegironi , "404 Page not found"

**Comment by davidegironi** [comment]
@macgyver76 try this one: https://file.town/download/4f5lfr5w5n4lgry22qp9nrrrj

**Comment by macgyver76** [comment]
Yup, that's better. Translations works fine. Would that feature be included in next release of ADGV as nuget package?

**Comment by davidegironi** [comment]
Yes, I think in a few weeks. Thank you for your check!

**Comment by davidegironi** [comment]
@macgyver76 now published on nuget
