### ISSUE TITLE
Change Dataset or Select Statement at Runtime

### ISSUE THREAD

**Issue by chrisheltzel** [davidegironi/advanceddatagridview#29]
Can anyone confirm if AdvancedDataGridView works with a DataSet and TableAdapter programmatically set at runtime?

My program allows a user to select a database and a table or query at runtime to displays the contents.  The following snippet is an example where oleConn is the connection to a selected database and sSQL is the select statement for the table/view specified at runtime.

oleAdapter = New OleDb.OleDbDataAdapter
oleAdapter.SelectCommand = New OleDb.OleDbCommand(sSQL, oleConn)
oleAdapter.Fill(oleDataSet)
advgControl.DataSource = oleDataSet.Tables(0)

When I swap in the ADGV, data is populated properly but the sorting and filtering do not work.  The drop down appears to show the primary key values for the first field I try to filter and is empty for any other field I select.

Does ADGV only work through the Data Source wizard at design time?

**Comment by davidegironi** [comment]
It should works but you have to make some changes to your design i think. The simpler thing is to use a BindingSource. Look at the ADGV sample project.

**Comment by chrisheltzel** [comment]
I found the specific problem which was related to my use of DataGridViewTextBoxColumn in the grid. Prior to loading data I would configure each column with code like this (where dtColumns contains formatting info):
 
colTextBox = New DataGridViewTextBoxColumn
With colTextBox
  .HeaderText = dtColumns.Rows(i)("ColumnAlias")
  .DataPropertyName = dtColumns.Rows(i)("ColumnName")
  .DefaultCellStyle.Alignment = dtColumns.Rows(i)("Alignment")
  .DefaultCellStyle.Format = dtColumns.Rows(i)("Format")
End With
adgvControl.Columns.Add(colTextBox)
 
The ADGV filtering and sorting started to work properly when I replaced the above code with the following: 
 
sColName = dtColumns.Rows(i)("ColumnName")
sColAlias = dtColumns.Rows(i)("ColumnAlias")
adgvControl.Columns.Add(sColName, sColAlias)
adgvControl.Columns(sColName).DataPropertyName = sColName
adgvControl.Columns(sColName).DefaultCellStyle.Alignment = dtColumns.Rows(i)("Alignment")
adgvControl.Columns(sColName).DefaultCellStyle.Format = dtColumns.Rows(i)("Format")
 
Hopefully this information helps if others have this problem.

**Comment by davidegironi** [comment]
Thank you for sharing your solution!
