### ISSUE TITLE
Filtering Issue using IN clause instead of NOT IN

### ISSUE THREAD

**Issue by OceanAirdrop** [davidegironi/advanceddatagridview#3]
First of all, I want to say GREAT project.  Good stuff.

I have found an issue, when filtering out the zeros (0) using the checkbox. 

After you do this, when you edit the value of one the cells "in the column that was filtered", the row then disappears from the grid and when the event handler for CellEndEdit fires the value is null for the row/column that was edited.

I tracked the issue to the use of the "IN" clause in the filtering code.

**DESCRIPTION OF PROBLEM**

For example, say you have 5 rows with the following values:

row 1 = 100
row 2 = 0
row 3 = 200
row 4 = 0
row 5 = 300

Then the user selects the filter menu on the column and ticks the checkbox to "not" display zeros. In the background your DataTable filter looks like this:

[{0}] IN (100, 200, 300)

The filter is including all the values that are ticked.  The grid then looks (obviously) like this:

row 1 = 100
row 3 = 200
row 5 = 300

Now, if the user modifies row 3 to equal 600, becauase 600 is not in the datatable "IN" clause filter the row disapears from the grid, and even the CellEndEdit doesnt capture the users modification.

**FIX FOR PROBLEM**

I swapped the code from an "IN" to a "NOT IN" and it seems to fix this problem.  So the code finds out all the cells that are NOT ticked and uses a "NOT IN" clause for the filter.

e.g: [{0}] NOT IN (0, 1)

Then, when the user modifies any of the value, the row doesnt disppear because the values still satisfy the filter clause.

**CODE I HAVE MODIFIED**

The code that I have changed is in the SetCheckListFilter() function.

I changed 4 lines in total: 

Original Line = "&& n.CheckState != CheckState.Unchecked" 
Changed Line = "&& n.CheckState == CheckState.Unchecked"

Original Line = "FilterString += "[{0}] IN (" + filter + ")";" 
Changed Line = "FilterString += "[{0}] NOT IN (" + filter + ")";"

Original Line = FilterString += "Convert([{0}],System.String) IN (" + filter + ")";" 
Changed Line = "FilterString += "Convert([{0}],System.String) NOT IN (" + filter + ")";"

Also you didn't specify decimal in your list of datatypes (thats what I am using to represent money)

I have added: "DataType == typeof(decimal)" to the list of datatypes in that funtion.

Sorry. I am sure there is a better way of showing you the code I have modified instead of writing it out here! 

**SUMMARY**

I just wanted to send this to you to get your thoughts on the fix I have applied.

Thanks.

**Comment by davidegironi** [comment]
Hello and thank you for your feedback.

 - DataType == typeof(decimal)

fixed, thank you

 - Reverse logic (NOT IN) for Menu Strip filter

I've add a selector for this type of logic you can set this logic by **SetMenuStripFilterNOTINLogic** function.
I use this as ReadOnly, that's the reason I've never came up to this issue. I still prefer the IN logic cause most of the time this filter will work as IN logic, i mean most of the time i will check the things i would like to filter. Also the NOT IN logic should take up performance issue on big dataset.
This the reason why i left default mode as IN logic.
For NOT IT logic the best option would be a "Custom Filter".
You can take a look at the modded code here: http://expirebox.com/download/263576cbad2b1bb8a2436253ed82a09a.html (will expire in 48h)
Let me know what do you think about this, then i will commit it to master.

**Comment by OceanAirdrop** [comment]
Thank you for looking into this.

I like your approach to the fix. The ability to "toggle" between the the 2 filter options is a good way of addressing this problem.  

I have just checked and your code update and that will fix my problem. 

Thanks.

**Comment by davidegironi** [comment]
Thank you, I will take it to a production software I've here, then after it's tested I will update this as release and close this issue.
