### ISSUE TITLE
System.Data.SyntaxErrorException If bool is filtered and there is a whitespace in the column name

### ISSUE THREAD

**Issue by sepp89117** [davidegironi/advanceddatagridview#30]
Hello, I had a problem when I wanted to filter a column with bool. The column name contains a space. I added square brackets in your code and the problem was solved.

File: MenuStrip.cs
Line: 646
Original: FilterString + = "{0} =" + filter;
New: FilterString + = "[{0}] =" + filter;

greeting

**Comment by davidegironi** [comment]
Hello @sepp89117 , I've checked my code. I've run my sample project you can compile here, clear the sort on double column, and then sorted the boolean one. It works here. Can you please do this check?
Thank you.

**Comment by sepp89117** [comment]
Hello @davidegironi, I have checked the lib according to your instructions.
Of course it works. The problem is another! If the column has a name of two words and you try to filter false or true, then there is the exception. The column name must be in square brackets, then it works.
Please change in your sample the column name as a test to "boolean col" or something similar, then you get the error.

greeting

**Comment by davidegironi** [comment]
Thank you!
Now i get this. I've just publish a new release with this fix. Really thank you! The nuget package is beeing published.

**Comment by sepp89117** [comment]
Absolutely nothing to thank! ADGV is great and I am happy that I could contribute a very small part!
