### ISSUE TITLE
Checkbox filters not localized in French

### ISSUE THREAD

**Issue by DragonBack74** [davidegironi/advanceddatagridview#31]
Hi I have a small issue around filter translations concerning checkbox type columns.
The filters say True / false where they should say Vrais/Faux or Oui/Non ..
Can this be overwritten or fixed ?
Thanks !!!
<img width="237" alt="chkbox_filter" src="https://user-images.githubusercontent.com/52431515/60472952-471c9500-9c6b-11e9-9752-77fbd1b70419.png">

**Comment by davidegironi** [comment]
Hello @DragonBack74 , thank you for your feedback. Check out the new release, you should be able to add the ADGVNodeSelectTrue and ADGVNodeSelectFalse fields to the language file.
Let me know if it's all ok.
nuget package is beeing published.

**Comment by DragonBack74** [comment]
Hello Davide,

Thank you for that quick reply and fix !!!!

Can you tell me where is the language file?

Also is there a way to remove filtering on one column at runtime?

Jérôme

 

De : Davide Gironi <notifications@github.com> 
Envoyé : mercredi 3 juillet 2019 21:07
À : davidegironi/advanceddatagridview <advanceddatagridview@noreply.github.com>
Cc : DragonBack74 <jerome.claude@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [davidegironi/advanceddatagridview] Checkbox filters not localized in French (#31)

 

Hello @DragonBack74 <https://github.com/DragonBack74>  , thank you for your feedback. Check out the new release, you should be able to add the ADGVNodeSelectTrue and ADGVNodeSelectFalse fields to the language file.
Let me know if it's all ok.
nuget package is beeing published.

**Comment by davidegironi** [comment]
Look at the lang.json file in the sample project.
No, it's not possible to remove filtering on one column at runtime. If you add this function please share this with the community, it will be a pleasure to merge this mod.
