### ISSUE TITLE
[Suggestion] Writing in the node filter on big data sets

### ISSUE THREAD

**Issue by Novido** [davidegironi/advanceddatagridview#32]
I'm working on quite large data sets and when I try to write a filter in the text box above the tree node, it updates the result after every character. Having 10k+ unique posts makes that update process tedious. 

What i would want is to have the tree node update first when the user is done writing what he is looking for. And also to make it asynchronous so the entire computer won't freeze for every search. 

I haven't find the place in the code myself, where this is happening. So that's why I'm commenting here to see if my suggestion is even possible?

**Comment by davidegironi** [comment]
Hello @Novido , it's in the MenuStrip.cs file, but's there a little bit of code around to do what you need. At present I'm fully involved in other projects, but if I had time I'll take a look on it. Meanwhile, if you want to implement this, please share it in this repository.
