### ISSUE TITLE
Date filtering not working with SQL source

### ISSUE THREAD

**Issue by RustonPaving** [davidegironi/advanceddatagridview#33]
When using a datatable/table adapter that's getting data from a SQL table filtering on a SQL date column does not seem to work.  It treats the data as generic text and doesn't show the more advanced date filtering where you can drill into the years/months.  I've confirmed the column in the data table is configured with the appropriate DateTime datatype.  I'm using VB.Net.

I've also used the SetFilterDateAndTimeEnabled function on the relevant column and that does not help

**Comment by davidegironi** [comment]
Please refer to the sample provided in code, there you can find a way to make the filter works. Also, take a look here: https://github.com/davidegironi/advanceddatagridview/issues/24 it may be interesting to you.

**Comment by RustonPaving** [comment]
I found that when I specified the datasource in code it worked as expected.  But when I did it through the GUI it would treat dates as strings.  I didn't change anything else about my code.

**Comment by EllebiVr** [comment]
I have the same problem.

**Comment by RustonPaving** [comment]
Glad to hear I'm not the only one :)  In case it could help anyone else, here was my final solution...

```
Dim ds As New DataSet1TableAdapters.MatTixTableAdapter
Dim bds As New BindingSource With {.DataSource = ds.GetData}
adgvTicketList.DataSource = bds
```

I still think there's an underlying problem, I don't know why this wouldn't work when configured thru the GUI.

**Comment by davidegironi** [comment]
Thank you for sharing this solution here.

**Comment by EllebiVr** [comment]
I think the problem is that with the GUI the columns are set by default as DataGridViewTextBoxColum

**Comment by Usernumber76** [comment]
I ran into the same issue when using the GUI to bind a SQL table.  I think it has something to do with valuetypes not being applied until runtime so they appear as default text cells.  If I use the GUI and remove all DateTime fields from the DataGridView, then add them in code, it causes the addcolumn event to fire and applies the new headercell info.

**Comment by DarkNecrom** [comment]
Hello,

I have solved it by checking the DataType in the Show event of MenuStrip.cs and comparing it with the type of the list of values.
`if (DataType == typeof(System.Object)) DataType = vals.First().ValueType;`

This way it detects the field type well when using the GUI.

The problem is caused by using the GUI adding the columns to the DataGrivView without their data types.

**Comment by sacalvario** [comment]
> Glad to hear I'm not the only one :) In case it could help anyone else, here was my final solution...
> 
> ```
> Dim ds As New DataSet1TableAdapters.MatTixTableAdapter
> Dim bds As New BindingSource With {.DataSource = ds.GetData}
> adgvTicketList.DataSource = bds
> ```
> 
> I still think there's an underlying problem, I don't know why this wouldn't work when configured thru the GUI.

**Comment by sacalvario** [comment]
> Glad to hear I'm not the only one :) In case it could help anyone else, here was my final solution...
> 
> ```
> Dim ds As New DataSet1TableAdapters.MatTixTableAdapter
> Dim bds As New BindingSource With {.DataSource = ds.GetData}
> adgvTicketList.DataSource = bds
> ```
> 
> I still think there's an underlying problem, I don't know why this wouldn't work when configured thru the GUI.

hi, could you pass that code to c #?

**Comment by DarkNecrom** [comment]
Try this
![MenuStrip](https://user-images.githubusercontent.com/75834314/154531256-6cc10698-0bf1-42f8-aeb9-6476d639aee5.JPG)
s

**Comment by AJMena** [comment]
I suppose then I must compile AdvancedDataGridView myself and use the new .dll.
I'm having some problems opening the code, but I'll try to fix it and compile.
Can't this be added to the next release?

**Comment by AJMena** [comment]
Sorry for the late respond.

DarkNecrom's code fixed it but without the if. Like this:

            try
            {
                DataType = vals.First().ValueType;
            }
            catch
            {
                DataType = typeof(System.String);
            }

The solution only fixed the filters. The sorts are still wrong. They appeared like string type. Is there any way to fix the sorts?

![SortIncorrectType](https://user-images.githubusercontent.com/55789664/158579566-f36dfe5e-a56e-41f0-8b86-a6ed7d737b76.png)

Thank you.
