### ISSUE TITLE
Advanced DataGridView on manual columns?

### ISSUE THREAD

**Issue by namnntt** [davidegironi/advanceddatagridview#34]
I am trying to put a filter on datagridview with ADGV However, when I create Datetime value columns by manually the filter does not display filtering by the Year, Month, and Day values. When the column is created automatically, in runtime this columns shows exactly how to filter. I want to create these DateTime value columns by manually. What should I do?
![Auto](https://user-images.githubusercontent.com/12720560/66158332-e88efa80-e64f-11e9-90f8-c47ab6226ac3.jpg)
**### By Auto column**
![Manually](https://user-images.githubusercontent.com/12720560/66158333-e88efa80-e64f-11e9-98b4-3b6682118ffd.jpg)

**Comment by davidegironi** [comment]
I do not understaind what are you asking, what do you mean with "by manually"? The way the filter expose values depends on the Type of the underline row, You should define the proper type on the row you want to filter.

**Comment by namnntt** [comment]
> I do not understaind what are you asking, what do you mean with "by manually"? The way the filter expose values depends on the Type of the underline row, You should define the proper type on the row you want to filter.

this is manual columns 
![Manually](https://user-images.githubusercontent.com/12720560/66256320-cfed2480-e7b6-11e9-83f0-7adb1172d13e.jpg)

**Comment by davidegironi** [comment]
You should bind it to a BindingSource, and set the DataPropertyName, or you could pragmatically set the column type by Name using the DataType property.
