### ISSUE TITLE
Grid view columnheader(dropdown list) have duplicated values

### ISSUE THREAD

**Issue by abbastoz** [davidegironi/advanceddatagridview#35]
Hi, how can i prevent duplicated values in filter ( dropdown list). There is an example below. 
![D32B7557-142F-42D7-9E96-2B6CC00EFBE5](https://user-images.githubusercontent.com/45153199/66330293-c7245c00-e938-11e9-8acb-769e7c415150.jpeg)

**Comment by davidegironi** [comment]
Where did you get this screenshot?

**Comment by abbastoz** [comment]
it was just an example. Here is the actual screen-shot,  Why is it duplicated? Can you prevent duplicates.? 
![duplicate](https://user-images.githubusercontent.com/45153199/66515988-c3cfd280-eae8-11e9-857c-84c0f4871295.jpg)

**Comment by abbastoz** [comment]
even one or two of them selected, the filtered result is same.

**Comment by abbastoz** [comment]
And also is there a way clear all filter,i use datagridview1.ClearFilter(), this is works but filter checkbox situation does not changes.

**Comment by davidegironi** [comment]
Hello, i do not have duplicate, edit the sample as follow to insert just two lines, same values. You should find no duplicate in the list. I do encounter the ClearFilter problem to. Check the sample button "Clear Filter And Sort".

`
/*for (int i = 0; i <= 100; i++)
            {
                object[] newrow = new object[] {
                    i,
                    (decimal)i*2/3,
                    i % 2 == 0 ? (double)i*2/3 : (double)i/2,
                    DateTime.Today.AddHours(i*2).AddHours(i%2 == 0 ?i*10+1:0).AddMinutes(i%2 == 0 ?i*10+1:0).AddSeconds(i%2 == 0 ?i*10+1:0).AddMilliseconds(i%2 == 0 ?i*10+1:0).Date,
                    DateTime.Today.AddHours(i*2).AddHours(i%2 == 0 ?i*10+1:0).AddMinutes(i%2 == 0 ?i*10+1:0).AddSeconds(i%2 == 0 ?i*10+1:0).AddMilliseconds(i%2 == 0 ?i*10+1:0),
                    i*2 % 3 == 0 ? null : i.ToString()+" str",
                    i % 2 == 0 ? true:false,
                    Guid.NewGuid(),
                    sampleimages[r.Next(0, 2)],
                    TimeSpan.FromHours(10).Add(TimeSpan.FromMinutes(r.Next(maxMinutes)))
                };

                _dataTable.Rows.Add(newrow);
            }*/

            {
                int i = 1;
                object[] newrow = new object[] {
                    i,
                    (decimal)i*2/3,
                    i % 2 == 0 ? (double)i*2/3 : (double)i/2,
                    DateTime.Today.AddHours(i*2).AddHours(i%2 == 0 ?i*10+1:0).AddMinutes(i%2 == 0 ?i*10+1:0).AddSeconds(i%2 == 0 ?i*10+1:0).AddMilliseconds(i%2 == 0 ?i*10+1:0).Date,
                    DateTime.Today.AddHours(i*2).AddHours(i%2 == 0 ?i*10+1:0).AddMinutes(i%2 == 0 ?i*10+1:0).AddSeconds(i%2 == 0 ?i*10+1:0).AddMilliseconds(i%2 == 0 ?i*10+1:0),
                    i*2 % 3 == 0 ? null : i.ToString()+" str",
                    i % 2 == 0 ? true:false,
                    Guid.NewGuid(),
                    sampleimages[r.Next(0, 2)],
                    TimeSpan.FromHours(10).Add(TimeSpan.FromMinutes(r.Next(maxMinutes)))
                };
                _dataTable.Rows.Add(newrow);
                i = 1;
                newrow = new object[] {
                    i,
                    (decimal)i*2/3,
                    i % 2 == 0 ? (double)i*2/3 : (double)i/2,
                    DateTime.Today.AddHours(i*2).AddHours(i%2 == 0 ?i*10+1:0).AddMinutes(i%2 == 0 ?i*10+1:0).AddSeconds(i%2 == 0 ?i*10+1:0).AddMilliseconds(i%2 == 0 ?i*10+1:0).Date,
                    DateTime.Today.AddHours(i*2).AddHours(i%2 == 0 ?i*10+1:0).AddMinutes(i%2 == 0 ?i*10+1:0).AddSeconds(i%2 == 0 ?i*10+1:0).AddMilliseconds(i%2 == 0 ?i*10+1:0),
                    i*2 % 3 == 0 ? null : i.ToString()+" str",
                    i % 2 == 0 ? true:false,
                    Guid.NewGuid(),
                    sampleimages[r.Next(0, 2)],
                    TimeSpan.FromHours(10).Add(TimeSpan.FromMinutes(r.Next(maxMinutes)))
                };
                _dataTable.Rows.Add(newrow);
            }`
