### ISSUE TITLE
Option to disable custom filtering

### ISSUE THREAD

**Issue by jupe** [davidegironi/advanceddatagridview#37]
Is it possible to disable custom filtering ? If not, please could you add option for it, thanks.

**Comment by davidegironi** [comment]
Dear @jupe , sorry for my delay.
Check this code out and let me know https://file.io/VQ2yrd
Functions DisableFilterCustom, EnableFilterCustom, SetFilterCustomEnabled has been added.
Let me know.

**Comment by tumbelo** [comment]
Hi, @davidegironi,
 
> Check this code out and let me know https://file.io/VQ2yrd
I got 404 when attempting to access that....

**Comment by davidegironi** [comment]
@tumbelo think it was expired. Try this one, let me know. https://file.io/iIhG56
Thank you.

**Comment by jupe** [comment]
any chances to push changes to git instead?

**Comment by tumbelo** [comment]
I still got 404 with a new link. I totally agree with @jupe, that it would be easier and more "standard way" to have changes/proposals in Git. Could you add a feature branch for example?

**Comment by davidegironi** [comment]
I prefer not to add a new branch, it's a kind of... i don't know... my way of git-ting :)
Let's try this one: https://filebin.net/cwlx2iu5t9uw4hnn
If this one also do not work, let me know, I'll do an "experimental"(or something like that) branch.
Thank you for understanind.

**Comment by tumbelo** [comment]
Thank you - that worked! I will give a try for it, but it's not before next week. So, let's keep in touch. By the way: if/when it works like assumed, you are going to push changes to master or do you plan to keep disabling unofficial version?

**Comment by davidegironi** [comment]
@tumbelo thank you for testing. Yes of course, pushing changes to master and the new version to nuget.

**Comment by tumbelo** [comment]
I finally had time to check this! Works like assumed. Thank you! Good work!

So, go for master from my point of view :) 

In fact for my application "SetFilterCustomVisibility" would be much better option. Could you add also that? I mean: I will never let user use custom filters, so user may be confused if custom filters are visible (even grayed as inactive). Would be clearer, if there wouldn't be custom filter menu items visible at all.

**Comment by davidegironi** [comment]
Published to master, and nuget. As for the SetFilterCustomVisibility I'll do this as soon as i get time. Thank you.

**Comment by tumbelo** [comment]
Excellent, thank you!!!

**Comment by tumbelo** [comment]
I will open issue for SetFilterCustomVisibility :)
