### ISSUE TITLE
SetFilterChecklistEnabled and slow checklist filters

### ISSUE THREAD

**Issue by siwix1** [davidegironi/advanceddatagridview#39]
Thanks for making this control. The excel like filters are great, I just have a question regarding the checklistfilters. 

            foreach (DataGridViewColumn col in applicationGridView.Columns)
            {
                applicationGridView.SetFilterChecklistEnabled(col, show);
            }

I1m working with large datasets (100K+) . Unfortunately, the checklist filters are very slow with that many rows. So I attempted to turn them off using the code above.   
I have 4 grids displaying at the same time using the same inherited control. 
In the first grid I get Filter list is disabled.

But on the next grid the checklistfilter is showing, disabled as in not selectable, and also very slow again. 

![62CB04DC-0A82-4642-A1E6-F7E23A019479_4_5005_c](https://user-images.githubusercontent.com/27358078/79243951-a32e6e00-7eb9-11ea-91a3-d893063f57ae.jpeg)

![90D2C90A-F80A-4F6F-8E3B-F99C59B420E1_4_5005_c](https://user-images.githubusercontent.com/27358078/79244631-775fb800-7eba-11ea-969c-d9ae7bd7d8b6.jpeg)

Thanks again.

**Comment by siwix1** [comment]
It must have been just something in my test project's tab controls. In my actual user control it worked. It would be nice though, if you could limit the number of items shown like Excel does, to speed it up a little I mean.  Thanks.

**Comment by davidegironi** [comment]
Thank you for sharing. I've checked it this morning but I've not time to reply you. That could be a nice feature that I may implement in some next release.
