### ISSUE TITLE
Dates not filtering when SetMenuStripFilterNOTINLogic(true) is set.

### ISSUE THREAD

**Issue by OceanAirdrop** [davidegironi/advanceddatagridview#4]
Hi there,

Thank you again for the previous "SetMenuStripFilterNOTINLogic()" addition.  It is working perfect for me.

I have, however found a side-effect issue when setting MenuStripFilterNOTINLogic to true to do with filtering of dates.  

I have a fix which is working for me but just wanted to pass it via you.

DESCRIPTION OF PROBLEM

In the demo app, if you call the function: SetMenuStripFilterNOTINLogic(true) passing true through, then try filtering the dates column they no longer work.

FIX FOR PROBLEM

The code I have changed is in the MenuStrip.cs file in the SetCheckListFilter() function.

When you filter on a date the function BuildNodesFilterString() gets called.  For some reason it fails when selecting dates!!

    string filter = BuildNodesFilterString(
        (IsFilterNOTINLogicEnabled ?
            checkList.Nodes.AsParallel().Cast<TreeNodeItemSelector>().Where(
            n => n.NodeType != TreeNodeItemSelector.CustomNodeType.SelectAll
                && n.NodeType != TreeNodeItemSelector.CustomNodeType.SelectEmpty
                && n.CheckState == CheckState.Unchecked
        ) :
        checkList.Nodes.AsParallel().Cast<TreeNodeItemSelector>().Where(
            n => n.NodeType != TreeNodeItemSelector.CustomNodeType.SelectAll
                && n.NodeType != TreeNodeItemSelector.CustomNodeType.SelectEmpty
                && n.CheckState != CheckState.Unchecked
        ))
    );

I have modified that section of code to the following and it now works for me.  Essentially I am checking to see if FilterNOTIn logic is enabled and the column being filtered is of type DateTime.

The new code looks like this:

    IEnumerable<TreeNodeItemSelector> tempList = null;
    if (IsFilterNOTINLogicEnabled == true && DataType != typeof(DateTime))
    {
        tempList = checkList.Nodes.AsParallel().Cast<TreeNodeItemSelector>().Where(
            n => n.NodeType != TreeNodeItemSelector.CustomNodeType.SelectAll
                && n.NodeType != TreeNodeItemSelector.CustomNodeType.SelectEmpty
                && n.CheckState == CheckState.Unchecked);
    }
    else
    {
        tempList = checkList.Nodes.AsParallel().Cast<TreeNodeItemSelector>().Where(
            n => n.NodeType != TreeNodeItemSelector.CustomNodeType.SelectAll
                && n.NodeType != TreeNodeItemSelector.CustomNodeType.SelectEmpty
                && n.CheckState != CheckState.Unchecked
        );
     }

    string filter = BuildNodesFilterString(tempList);

In the demo app, this code works for filtering of dates. 

Thanks.

**Comment by davidegironi** [comment]
Hello and **thank you** again for this feedback, very descriptive and with a resolution proposal, is not for all to be so accurate.
It cames out that there's this issue even for TimeSpan and bool, so I've edit line 515 from
```
(IsFilterNOTINLogicEnabled ?
```
to
```
(IsFilterNOTINLogicEnabled && (DataType != typeof(DateTime) && DataType != typeof(TimeSpan) && DataType != typeof(bool)) ?
```
Note: there are two useless parentesis, but I've left there for clarity.
Check it out and let me know if it works for your, then i will close this issue and post the resolution.

Just recompile with this change. For completeness my recompiled release is available at this address (expires in 2 days) : http://expirebox.com/download/56b9218ec58509d56719dee42c328a2e.html

**Comment by davidegironi** [comment]
Thank you.
