### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by naji-makhoul** [davidegironi/advanceddatagridview#40]
datagridview not support rtl

![rtl1](https://user-images.githubusercontent.com/5232373/80308966-9889a800-87da-11ea-8e4b-f2a2c9516e93.jpg)

![rtl2](https://user-images.githubusercontent.com/5232373/80308971-9e7f8900-87da-11ea-8b3a-63a5c7bd66f0.png)

**Comment by davidegironi** [comment]
@naji-makhoul thank you for feedback. This datagrid do not support RightToLeft, if you are going to implement this feature please share with me. Until that you could force the left to right direction of your AdvancedDataGridView instance by setting the RightToLeft property (ex. advancedDataGridView_main.RightToLeft = RightToLeft.No).
I'm going to forced to left to right direction changing the constructor of the AdvancedDataGridView to something like this:

```
public AdvancedDataGridView()
{
    RightToLeft = RightToLeft.No;
}
```
