### ISSUE TITLE
hide or show column panel

### ISSUE THREAD

**Issue by michaelbrucelin** [davidegironi/advanceddatagridview#44]
If add a panel to control the Visible property of all columns, it would be great.
Like this, when you right-click a column header, a panel will pop up, you can control to hide the current column, display all columns, and display and hide all other columns. When the mouse click other position of the DataGridView, the panel will disappears.
![datagridview column hidden panel](https://user-images.githubusercontent.com/36387756/88247471-62bc6880-ccd0-11ea-8d0e-b706e0cece19.png)

**Comment by davidegironi** [comment]
Hello @michaelbrucelin , thank you for suggestion. I had to think about this, maybe if could be added to the SearchToolbar component.
By now you should make visible or not setting the column Visible proporty, like so `advancedDataGridView_main.Columns["columnname"].Visible = false;`
Anyway, if you are going to build this feature, please share with me.

**Comment by michaelbrucelin** [comment]
This feature has not been built yet, if I build this feature, I must share it with you, although my code level is limited.
