### ISSUE TITLE
filter dialog slow to open with large datagridview

### ISSUE THREAD

**Issue by processor-gis** [davidegironi/advanceddatagridview#45]
I'm using a datagridview that has over 100k rows and its very slow to get the filtering dialog box to appear. It usually takes 5 or 6 minutes to open but after that the filtering works fine. I love this control but is there any possible way to speed it up? I think the issue might be with populating the unique values in the filtering dialog box.

**Comment by davidegironi** [comment]
Hello @processor-gis , yes, that's due to the Filter list population, you can disable it by using the SetFilterChecklistEnabled method, find an example on the sample project. If you find a faster way to build this, please share with me.
