### ISSUE TITLE
Sort string contains a property that is not in the IBindingList.

### ISSUE THREAD

**Issue by Etos7** [davidegironi/advanceddatagridview#47]
Advanceddatagridview is crashing when trying to  sort any column of any type:

> `System.ArgumentException
>   HResult=0x80070057
>   Message=Sort string contains a property that is not in the IBindingList..
>   Source=System.Windows.Forms
>   Ślad stosu:
>    at System.Windows.Forms.BindingSource.ParseSortString(String sortString)
>    at System.Windows.Forms.BindingSource.set_InnerListSort(String value)
>    at Zuby.ADGV.AdvancedDataGridView.TriggerSortStringChanged()
>    at Zuby.ADGV.AdvancedDataGridView.Cell_SortChanged(Object sender, ColumnHeaderCellEventArgs e)
>    at Zuby.ADGV.ColumnHeaderCell.MenuStrip_SortChanged(Object sender, EventArgs e)
>    at System.EventHandler.Invoke(Object sender, EventArgs e)
>    at Zuby.ADGV.MenuStrip.SortDESCMenuItem_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>    at Microsoft.VisualStudio.Tools.UserControlTestContainer.Main(String[] args)
> `

Code that I'm running:

```
>  private void BindDataTest()
>         {
>             sqlConnnectionString = @"Server=L674\SQLEXPRESS;Database=devDB;Trusted_Connection=True;";
>             sqlQuery = @"SELECT * FROM devTable;";
> 
>             SqlConnection sqlCon = new SqlConnection(sqlConnnectionString);
>             SqlDataAdapter sqlDA = new SqlDataAdapter(sqlQuery, sqlCon);
>             
>             sqlDT = new DataTable();
>             sqlDS = new DataSet();
> 
>             try
>             {
>                 sqlCon.Open();
>                 sqlDA.Fill(sqlDS, "devTable");
>                 sqlCon.Close();
>                 
>  
>                 bindingSource.DataSource = sqlDS;
> 
>                 dataGrid.SetDoubleBuffered();
>                 dataGrid.DataSource = bindingSource;
>                 dataGrid.DataMember = "devTable";
> 
>             }
>             catch (Exception e)
>             {
>                 MessageBox.Show(e.Message, "Exception in SQLTable");
>             }
> 
>         }
```
![image](https://user-images.githubusercontent.com/31066103/90239040-35725e80-de27-11ea-9c22-0e23137d8ed6.png)

Filter does not work too.

**Comment by davidegironi** [comment]
Hello @Etos7 , try setting the DataMember of the bindingsource, like in the sample project
