### ISSUE TITLE
Edit filter options

### ISSUE THREAD

**Issue by miguelmpn** [davidegironi/advanceddatagridview#48]
Hello, 

How can I edit the filter options in the columns?
My DGV is bound to a DataTable, but on the CellFormatting I change the cells in the column from blank to "FPGA", I would like this to be reflected on the filters.

![Image of DataGridView](https://i.ibb.co/hWn2ZPw/image.jpg)

Should I edit the cells in another way?

**Comment by davidegironi** [comment]
Hello @miguelmpn , if I've understand your need, you should take a look to the internationalization capabilities of ADGV. Loot at the "ADGVNodeSelectEmpty": "(Blanks)", fields of the json language file.
The AdvancedDataGridViewSample project will show you how to load custom language files.
