### ISSUE TITLE
Performance issue when binding multiple columns

### ISSUE THREAD

**Issue by supawix** [davidegironi/advanceddatagridview#50]
Steps to replicate
1. Add 200 - 300 columns in datatabe
2. bind to advanceddatagrid view

Expected Result:
-It should load fast just like normal datagridview.

Actual Result:
-Binding takes 2-3mins. Compare to normal gridview takes only a 1-2 secs

Hope this helps :)

**Comment by davidegironi** [comment]
Thank you @supawix 
Advanceddatagrid is not optimized for that amount of column, 200, 300 are "a lot", i mean, it's of out the gaussian distribution.
Anyway, you can check my sample here https://file.io/4WP29a7FLnZr, it's loading 100 rows on 300 columns in 10 seconds consuming 100Mb on my i5 Windows 10 PC.
