### ISSUE TITLE
Filtering on DateTime column with non-midnight time component doesn't return valid FilterString

### ISSUE THREAD

**Issue by will-scc** [davidegironi/advanceddatagridview#51]
I have a DateTime column with the format `dd/MM/yyyy HH:mm`:

![image](https://user-images.githubusercontent.com/31592644/99666755-4ef8f700-2a63-11eb-9c02-3c88ff563a42.png)

The values in the underlying DataSource are from a database so have non-midnight time componennts, e.g. `25/06/2020 12:22:44`.

This is recognised as a DateTime column:

![image](https://user-images.githubusercontent.com/31592644/99666933-91bacf00-2a63-11eb-92db-30a2a6be7603.png)

However, when you try to filter by a specific date (you can't filter by a specific hour) it returns no rows .

If I inspect the `FilterString` that's created, it is producing this:

`"((Convert([DATE RAISED], 'System.String') LIKE '%25/06/2020 00:00:00%'))"`

The reason this filter returns no rows is because, for example, `25/06/2020 12:22:44` is not like `25/06/2020 00:00:00` (due to the time component).

This same problem exists even if I force the column Format like this: `dgv.Columns("DATE RAISED").DefaultCellStyle.Format = "dd/MM/yyyy HH:mm:ss"`. The `FilterString` is still setting any time component to `00:00:00`. I assume this is because here we're only changing the displayed value and not the underlying value in the DataSource to which the filter is being applied.

If I truncate these dates at the database/query level, the filtering works. This is obviously not an ideal fix when I need to display the time component.

**Comment by davidegironi** [comment]
Hello @will-scc. DateTime converstion works if the format of the DateTime is the same of you o.s. culture
ref. line 722 MenuStrip.cs (sb.Append("(Convert([{0}], 'System.String') LIKE '%" + Convert.ToString((IsFilterDateAndTimeEnabled ? dt : dt.Date), CultureInfo.CurrentCulture) + "%')" + appx);)

I think the problem should be there.

Can you run the Sample project first and check if it works there for you?
Then you could try formatting the string with the data and time format of your culture.

**Comment by will-scc** [comment]
Hi @davidegironi, sorry for the delayed reply. I wanted to make sure I tested it on the machine that had the problem.

The sample project does work on the machine, so it's definitely an application-specific problem.

I've forced the formatting of the column to match the culture (`en-GB`):

![image](https://user-images.githubusercontent.com/31592644/100082740-86d7b400-2e40-11eb-9bf2-1d9fbfa63739.png)

However, this still isn't recognising the time component and, as a result, the filtering isn't working:

![image](https://user-images.githubusercontent.com/31592644/100082797-99ea8400-2e40-11eb-89ca-663294cca0a7.png)

As you can see, it's only picking up the dates not the times. My current culture is `en-GB` and the format is `dd/MM/yyyy HH:mm:ss`: `dgv.Columns("DATE RAISED").DefaultCellStyle.Format = "dd/MM/yyyy HH:mm:ss"`

Even if I remove all formatting and just have it default, it seems to be coming out as `dd/MM/yyyy HH:mm` which is odd. My data is loaded via ODP.NET from an Oracle database. If I inspect the underlying datasource the values are containing time components (evidence by forcing the formatting to show seconds).

Any ideas what might be going on here?

**Comment by will-scc** [comment]
Small bit of additional info. I've setup a brand new project to test this and the issue persists.

The complete code of my test:

```
private void Form2_Load(object sender, EventArgs e)
{
    var r = new Random();

    var dt = new DataTable();
    dt.Columns.Add("DATETIME", typeof(DateTime));

    for (int i = 0; i <= 10; i++)
    {
        var obj = new object[] { DateTime.Today.AddDays(r.Next(0, 7)).AddHours(r.Next(0, 12)).AddSeconds(r.Next(0, 30)) };
        dt.Rows.Add(obj);
    }

    advancedDataGridView1.DataSource = new BindingSource(dt, null);
}
```

**Comment by davidegironi** [comment]
I can not reproduce your behaviour.
Start from the Sample project provided in code. Does the "datetime"column work there?
To me it works, I've overriden the culture using App.Config (<add key="culture" value="en-GB" />)

![Capture](https://user-images.githubusercontent.com/1426098/100133175-b6111400-2e86-11eb-814f-29943889d2fd.JPG)

**Comment by will-scc** [comment]
I think I've narrowed down the problem to something related to loading data from databases (maybe the `DataAdapter`?

I've taken the working sample project and replaced the `SetTestData()` and `AddTestData()` methods to load data from my database with this query:

I tried this with both `Oracle.ManagedDataAccess.Client` and `System.Data.SqlClient` and the result is the same. One looking at an Oracle 11g database, the other an SQL Server database, so I don't think the issue is at the database level.

```
private void AddTestData()
{
    string conn = "<redacted>";

    //for SqlClient test this was changed to select getdate()
    string query = @"select sysdate-2 from dual
                         union
                     select sysdate-1 from dual
                         union
                     select sysdate from dual
                         union
                     select sysdate+1 from dual
                         union
                     select sysdate+2 from dual";

    using (OracleConnection cnx = new OracleConnection(conn))
    using (OracleCommand cmd = new OracleCommand(query, cnx))
    using (OracleDataAdapter da = new OracleDataAdapter(cmd))
    {
        //Tried thiis true and false just in case
        da.ReturnProviderSpecificTypes = false;
        da.Fill(_dataSet.Tables["TableTest"]);
    }
}
```
Which loads like this:

![image](https://user-images.githubusercontent.com/31592644/100210390-d8487780-2f02-11eb-9759-464264dbdf76.png)

The filtering then doesn't work:

![image](https://user-images.githubusercontent.com/31592644/100210337-cb2b8880-2f02-11eb-8d64-1a0f0928bd62.png)

Again, same problem in that the time component is not recognized. Note the FilterString.

I've double checked that the DataType of that column is definitely `System.DateTime`:

![image](https://user-images.githubusercontent.com/31592644/100211484-198d5700-2f04-11eb-9e2f-97dcb9d269a9.png)

I'm at a loss to think what the cause of this could be... Any ideas?

**Comment by davidegironi** [comment]
Instead of adding the full datatable, iterate the table adapter and fill a single row, then add the row to the dataset binded to the bindingdatasource of the grid.
You can also take a look of the method I'm using here in the DGUIGHF (https://github.com/davidegironi/dguighf/), like this one here https://github.com/davidegironi/dguighf/blob/master/DGUIGHFSample/FormPosts.cs
Another example on a working project here https://github.com/davidegironi/dentned
I'm using this strategy on a big project, never had problem with this, and it has obvious advantages to split the database structure to the view one. Hope this helps.

**Comment by will-scc** [comment]
Do you know why adding a complete DataTable would cause this behaviour? It's very weird that it only happens on DateTime columns in this specific situation, everything else works fine.

Having to change how to load data from my database into datatables by avoiding using `DataAdapter.Fill` is going to add a lot of unnecessary extra code, I'd rather try and fix the underlying bug...

**Comment by davidegironi** [comment]
I've never investigate on this. I prefer to uncouple the DataAdapter cause it's related to the DB you are using. You should try with other DB sources, or google for something like "DataAdapter.Fill datetime conversion". Also looking at your query, it performs an union between tables, at first i will try with just one table, than makes thing little more complex.
