### ISSUE TITLE
Filter/Sort doesn't work on multiple DataGridViewComboBoxColumn

### ISSUE THREAD

**Issue by RenaudSmith** [davidegironi/advanceddatagridview#53]
Hello,

When I add multiple DataGridViewComboBoxColumn, only the first one (on the left) can be filtered/sorted, the other ones display no values in the filtering and the event SortStringChanged is not firing.

![image](https://user-images.githubusercontent.com/77978209/105723953-a3b76300-5f27-11eb-8b28-7a8e368f68e4.png)

Here's how I add ComboBoxColumns :

```
for (int i = 0; i < advancedDataGridView1.Columns.Count; i++)
            {
                DataGridViewColumn column = advancedDataGridView1.Columns[i];
                //listCombobox is a list of string of column I want as combobox
                if (listComboBox.Contains(column.DataPropertyName))
                {

                    advancedDataGridView1.Columns.Remove(column.Name);
                    DataGridViewComboBoxColumn comboboxColumn = new DataGridViewComboBoxColumn();
                    comboboxColumn.DataPropertyName = column.Name;
                    comboboxColumn.HeaderText = column.Name;
                    comboboxColumn.DropDownWidth = 160;
                    comboboxColumn.Width = 150;
                    comboboxColumn.FlatStyle = FlatStyle.Flat;
                    LoadCombobox(comboboxColumn); //Here I set a DataSource, ValueMember and Display member from db
                    comboboxColumn.DataPropertyName = comboboxColumn.ValueMember;

                    advancedDataGridView1.Columns.Insert(i, comboboxColumn);
                }
                
            }
```

Thanks for your help.

**Comment by davidegironi** [comment]
Hello @RenaudSmith , please provide a full sample adding two Combobox column at in the AdvancedDataGridViewSample project.
Note: Your should not pragmatically remove the Column from the dataGridView, instead you should set the columns in the DataSource binded object.

**Comment by RenaudSmith** [comment]
Hello @davidegironi ,

Thanks for your response, here is the AdvancedDataGridViewSample with the problem.

I noticed it happens everytime you add more than one DataGridViewColumn programmatically, here I just add two empty DataGridViewTextBoxColumn (line 186 in FormMain.cs) and you can see the second one you click have the sorting box not working normally.
However if you clone a column from the gridview and add it, it works.

I don't know how to set the column to combobox in the datasource binded object, I need to fill the datasource of the comboboxcolumn from my database.

[advanceddatagridview-master.zip](https://github.com/davidegironi/advanceddatagridview/files/5873500/advanceddatagridview-master.zip)

**Comment by davidegironi** [comment]
Hello @RenaudSmith , check this out. It may helps you (expires 27 January 2021 at 20:06 (CET)). https://file.re/2021/01/26/advanceddatagridview-master/

**Comment by RenaudSmith** [comment]
Thank you very much !

**Comment by cadmonkey123** [comment]
hi I also do not know how to add my combobox data to a data table could point me in the right direction thanks (I am also using vb.net)
