### ISSUE TITLE
Checklist node double click filtering edge-case?

### ISSUE THREAD

**Issue by kincsespeti** [davidegironi/advanceddatagridview#54]
Hello,

so the checklist nodes have a feature to start a filtering by double clicking them (CheckList_NodeMouseDoubleClick).

This works fine, but if the user already filtered the nodes via the checkTextFilter textbox to the point of only having the "select all nodes" and one other node, then SetCheckListFilter's 
[`if (selectAllNode != null && selectAllNode.Checked)`](https://github.com/davidegironi/advanceddatagridview/blob/d40ba2bb6bd6a631409aad78836467d8d2041c71/AdvancedDataGridView/MenuStrip.cs#L627)
becomes true and the filtering is cancelled.

Steps to reproduce:
start sample
open the string column's menustrip
enter "blank" into the node filter
double click (Blanks) node

expected behavior: 
filter to blanks

possible fix:
check if the checkTextFilter is being used, this way the filter would activate even if all the nodes are selected but the nodes themselves are filtered
`if (selectAllNode != null && selectAllNode.Checked && String.IsNullOrEmpty(checkTextFilter.Text))`

![image](https://user-images.githubusercontent.com/12474985/107487649-af8d6100-6b86-11eb-9f7d-9f10dd871fbe.png)

**Comment by davidegironi** [comment]
Thank you for sharing this problem and the fix!
In the weekend I'll deploy a new fixed version.

**Comment by davidegironi** [comment]
Fix published with version 1.1.x.9
