### ISSUE TITLE
Windows Scale and Layout

### ISSUE THREAD

**Issue by oppman29** [davidegironi/advanceddatagridview#55]
Hi, thank you for this amazing advanced data grid view. 

Found an issue when the user changes the monitor display settings and changes the scale and layout option 
![scale and layout](https://user-images.githubusercontent.com/34219937/109040598-15580d80-769c-11eb-92a7-9efc4d622a9a.png)

The data filter cancel and  filter buttons along with the text get cutoff if they select for example 150% scale . 
 I made some changes to ResizeBox method in MenuStrip.cs and got it to scale correctly  by scaling the items. 
I also did some modifications for the custom filter to work ( otherwise this is also cut off)

There are two problems I can not solve , and I tried:

1* When  the user uses the grip to make the box bigger, when resizebox is called again on the grip release it breaks with my scaling.  For now I just disabled the grip if the scaling is not 100%.

2 * When the user selects a value like 200% in the scaling, the checkboxes are too small  ( couldn't figure out how to scale those)

thanks again and let me know if you would me to share what I updated .

**Comment by davidegironi** [comment]
Hello @oppman29 , thank you for posting this issue, and most of all for sharing your fixes. To now I think it could be ok even without the point 1* and 2* fixed. I you want you can send me the mods to apply, or request a pull. If you would like to go for the pull request, please fork this project and let me take a look to the mods before it.

**Comment by oppman29** [comment]
I was able to figure out issue 1 with the grip resize by doing some the scaling before it hits ResizeBox  on the constructor.  the issue with the textboxes couldnt figure out. 

Here are the files I changed :

MenuStrip.cs
FormCustomFilter.cs

and on the progam.cs just change the HighDPIEnabled to tru 

[Changes.zip](https://github.com/davidegironi/advanceddatagridview/files/6058119/Changes.zip)


I will try do a request to Pull but if you want to check them while i figure that out... we use Gitlab at work lol

**Comment by davidegironi** [comment]
No problem for the Pull request. I'm yet importing the mods in the code.
I'll try it in a few days and let you know. Really thank you for your help!

**Comment by davidegironi** [comment]
You can find the mods updated in the master branch, if is all ok for you in the next days I'll deploy a new version to nuget too.

**Comment by oppman29** [comment]
Yes that sounds amazing.. Thanks for your work and happy to help. I will check out this weekend on how to pull

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by davidegironi** [comment]
So, you check it out from the master branch of this repo? Did it pass your test?

**Comment by davidegironi** [comment]
I've double check it, it seems all ok to me. I'll close this.

**Comment by oppman29** [comment]
Thank you very much for the changes I downloaded the masted branch and all looks good.  Lenin

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by davidegironi** [comment]
That's great!
It also contains this pull request, fixed: https://github.com/davidegironi/advanceddatagridview/pull/57

**Comment by davidegironi** [comment]
Updated to nuget
