### ISSUE TITLE
Allow DataTable/DataView as DataSource with automatic sorting and filtering

### ISSUE THREAD

**Issue by kirsan31** [davidegironi/advanceddatagridview#60]
Hi. I was trying to set `DataTable` or `DataView` directly as `DataSource`. And this lead to filtering and sorting are stop working automatically.
What do you think about adding `DataTable` and `DataView`  to _supported_ DataSources (even default `DataGridView` are support them)?
Something like this:
[TriggerFilterStringChanged](https://github.com/davidegironi/advanceddatagridview/blob/6d85632f11acc71f9c412fd1f01ec7a709224b21/AdvancedDataGridView/AdvancedDataGridView.cs#L704):
```cs
if (this.DataSource is BindingSource datasource)
{
    datasource.Filter = filterEventArgs.FilterString;
}
else
{
    var dataView = (this.DataSource as System.Data.DataView) ?? (this.DataSource as System.Data.DataTable)?.DefaultView;
    if (dataView != null)
        dataView.RowFilter = filterEventArgs.FilterString;
}
```
[TriggerSortStringChanged](https://github.com/davidegironi/advanceddatagridview/blob/6d85632f11acc71f9c412fd1f01ec7a709224b21/AdvancedDataGridView/AdvancedDataGridView.cs#L552):
```cs
if (this.DataSource is BindingSource bindingSource)
{
    bindingSource.Sort = sortEventArgs.SortString;
}
else
{
    var dataView = (this.DataSource as System.Data.DataView) ?? (this.DataSource as System.Data.DataTable)?.DefaultView;
    if (dataView != null)
        dataView.Sort = sortEventArgs.SortString;
}
```
This will allow to skip using excess `BindingSource` or manual sorting.
Thanks.

**Comment by davidegironi** [comment]
Now I get this.
You mean something like this? for TriggerFilterStringChanged:

```csharp
//...
if (filterEventArgs.Cancel == false)
{
    if (this.DataSource is BindingSource bindingsource)
    {
        bindingsource.Filter = filterEventArgs.FilterString;
    }
    else if (this.DataSource is DataView dataview)
    {
        dataview.RowFilter = filterEventArgs.FilterString;
    }
    else if (this.DataSource is DataTable datatable)
    {
        if (datatable.DefaultView != null)
            datatable.DefaultView.RowFilter = filterEventArgs.FilterString;
    }
}
//...
```

**Comment by kirsan31** [comment]
Exactly. All my code from 1 post must replace code in this condition:
```cs
if (filterEventArgs.Cancel == false)
{
}
```
Sorry for misleading.

**Comment by davidegironi** [comment]
Hello, I'm posting your code update in the next deploy, if you want a preview download it from here: https://github.com/davidegironi/advanceddatagridview/issues/68#issuecomment-868566190
