### ISSUE TITLE
Filtering is not working 

### ISSUE THREAD

**Issue by AmeerMansour** [davidegironi/advanceddatagridview#61]
when using data source from object, Filters are not working at all .
![image](https://user-images.githubusercontent.com/47938924/113901675-6137bf80-97cf-11eb-9745-4c29a21c2a32.png)

**Comment by davidegironi** [comment]
Hello, look at the FAQ.
This is the link you are interested in https://github.com/davidegironi/advanceddatagridview/issues/24

**Comment by AmeerMansour** [comment]
this issue #24 uses deprecated dll for filtering list. will it better to use BindingListView ? will it work?
https://github.com/waynebloss/BindingListView
if yes , can it be handled within your lib ?

**Comment by davidegironi** [comment]
Thank you @AmeerMansour for this tip.
I prefer not to add library or dependency to this project. I think you can make this thing work using the TriggerSortStringChanged and TriggerFilterStringChanged handlers.
In you succed please share your solution in a new issue, I will add a FAQ like I've done with the #24 issue.
