### ISSUE TITLE
Changing the text in search bar

### ISSUE THREAD

**Issue by TinaRadenkovic** [davidegironi/advanceddatagridview#62]
Hi,

I am using AdvancedDataGridView Nuget package and I have a small issue with language translations in search bar. Is there any way to change the text shown on label, combobox and tooltips in search bar? I would like to translate it in Serbian. In the picture below I would like to change text: Search, (All Columns) and Value for Search and also text for all tooltips.
I tried to change text on those components and it works but when I run the program it reverts back to default value. 

![searchBar](https://user-images.githubusercontent.com/77357256/117193424-1c5d7380-ade3-11eb-84bc-e76e31af0bcc.png)

Thanks in advance

**Comment by davidegironi** [comment]
Hello,
Translation values are "ADGVSTBLabelSearch" and "ADGVSTBComboBoxColumnsAll" fields of the json translation file. To check it simply download the git files. In AdvancedDataGridViewSample project FormMain code set _testtranslationsFromFile to true, change values in the lang.json file and run the sample project. You should view the menu translated. You can use the AdvancedDataGridViewSample project code as snippet for your project.
