### ISSUE TITLE
Grouping items in DataGridView

### ISSUE THREAD

**Issue by helperman** [davidegironi/advanceddatagridview#63]
Didn't you think about adding a feature to group items in a datagrid?
Here is a good project (15 years old, though, but is still working):
https://www.codeproject.com/Articles/14388/OutlookGrid-grouping-and-arranging-items-in-Outloo

It could be the best control ever, with all-in-one functionality (sorting, filtering, grouping).

**Comment by davidegironi** [comment]
Hello @helperman 
Although this is an interesting feature, It's not in the todo list, at list in the next future. But if you integrate this, I can pull you git request.
