### ISSUE TITLE
Update datatable source -> filtered datagridview not updated

### ISSUE THREAD

**Issue by manukieli** [davidegironi/advanceddatagridview#64]
If the advanceddatagridview has not filter active and I update data of some rows, I can view the updated data to advanceddatagridview.
But when I filter some column and updated rows of the filtered row, advanceddatagridview is not updated.

**Comment by davidegironi** [comment]
Hello @manukieli , can you please provide a sample starting from the AdvancedDataGridViewSample project?

**Comment by manukieli** [comment]
Thank you @davidegironi for your answer, I've check the code of AdvancedDataGridViewSample and I've noticed that is was my mistake.
After update my code, now it work like a charm.
Thank you.

**Comment by davidegironi** [comment]
Happy to hear that. Good work.
