### ISSUE TITLE
Dynamic Filtering does not update when pressing backspace

### ISSUE THREAD

**Issue by peros550** [davidegironi/advanceddatagridview#65]
@davidegironi congrats for your work. I am having an issue in following step:
![AdvancedDataGridview](https://user-images.githubusercontent.com/12878906/118396207-1c693900-b657-11eb-8b51-c89f4dafe1ca.png)

When I enter characters in the red box as shown above, the list updates itself which works as expected. However, when I press backspace to delete characters, the lists no longer updates. Is that expected?

**Comment by peros550** [comment]
I am sorry. It looks this issue has already been solved in the latest dev version but not in the latest stable version. 
Before I close this issue I would like to make a question. When I run my app using Visual Studio debug mode, loading of the advanced datagridview takes a very long time to finish (maybe more than 30s). 

Running the same exe (compiled in debug mode) outside of VS, loads the datagridview as it should be, within a few seconds. 
Any idea why is that happening?

**Comment by davidegironi** [comment]
Thank you @peros550 
It's a bug in the new logic of MenuStrip.cs
Can you please check this version out? I think is fixed here: https://www.file.io/download/Plhu01ltumfV

**Comment by peros550** [comment]
@davidegironi many thanks! I may have actually tried an even older version that's why I thought it works. I'll try the one pointed out in the above link and get back to you. Any idea about the delay in loading the data when in debug mode?

**Comment by davidegironi** [comment]
Thank you for the test, i forgot about the delay.
It may due to the windows defender, check that the folder you are working on is not tested by defender. It happens to me when I'm working on the "Downloads" folder. It also may depends on "IntelliTrace", you should try disabling it from Options menu in Visual Studio.

**Comment by davidegironi** [comment]
Hello @peros550 , have you check it out?

**Comment by peros550** [comment]
@davidegironi I just tried to download the file but it's not available. Could you please re-upload?

**Comment by davidegironi** [comment]
Hello @peros550 , this is the new file: https://file.io/9Zr5wT7lA3c4

**Comment by davidegironi** [comment]
Hello @peros550 , did you success in the file download?

**Comment by peros550** [comment]
Yes, I downloaded the project. I had some issues opening it. It looks I need a copy of VS 2017, but I'm working on 2015. Nevertheless, I copied the AdvancedDataGridView.dll from the Release folder and compiled my program to test. The issue seems to remain and when typing the program becomes sluggish.

**Comment by davidegironi** [comment]
Hello, the dll on the release folder is not updated. Try the dll in the Debug folder in this zip here: https://file.io/YiElQ7ocOYQ4
I'll wait for your feedback.

**Comment by peros550** [comment]
Thanks for the quick feedback. This one works as expected! Will you upload it through nuget package manager?

**Comment by davidegironi** [comment]
Thank you for your feedback. This packages is now updated on nuget, maybe it will take a little for the propagation.

**Comment by peros550** [comment]
many many thanks!
