### ISSUE TITLE
Localization "pt-BR"

### ISSUE THREAD

**Issue by rockbr** [davidegironi/advanceddatagridview#66]
I did the translation to Portuguese Brazil "pt-BR"
[Localization-pt-BR.zip](https://github.com/davidegironi/advanceddatagridview/files/6529371/Localization-pt-BR.zip)

Thank you for sharing the project.

**Comment by rockbr** [comment]
Did not notice had sent the translation of another version.

[lang.zip](https://github.com/davidegironi/advanceddatagridview/files/6529883/lang.zip)

**Comment by davidegironi** [comment]
Thank you!, I'll add in the next version

**Comment by davidegironi** [comment]
Added in the sample project.

**Comment by vccrespo** [comment]
please how do i apply this translation in my project?
