### ISSUE TITLE
Enable/Disable Filter and Sort in Run time

### ISSUE THREAD

**Issue by nikjain75** [davidegironi/advanceddatagridview#69]
Hello, I want to Enable/Disable Filter and Sort in Run time.
I tried using this command, but it is not working as desired. 
_adgv1.FilterAndSortEnabled = True or
adgv1.FilterAndSortEnabled = False_ 

This works well from the IDE (Property list).
Anything i am doing wrong ? or is there any other way to do that. Please suggest.

**Comment by davidegironi** [comment]
Hello @nikjain75 
Use the SetSortEnabled and SetFilterEnabled methods.
Look at FormMain_Load method of Sample project.

**Comment by nikjain75** [comment]
> 
> 
> Hello @nikjain75
> Use the SetSortEnabled and SetFilterEnabled methods.
> Look at FormMain_Load method of Sample project.

Thank you for the superfast reply.
Actually I was looking to completely disable the filter including the Filter/Sort icons on the column header.
This is possible when I set the .FilterAndSortEnabled = False in IDE.

The methods you suggested only disables the filter, but the Filter/Sort icon is still visible and clickable in column header.

I am not getting why in code adgv1.FilterAndSortEnabled = False is not working.

**Comment by davidegironi** [comment]
Hello @nikjain75 ,

this is the behaviour of DisableFilterAndSort and EnableFilterAndSort methods. Try those two.
If can use FilterAndSortEnabled before attaching the dataset to the datagrid.

**Comment by nikjain75** [comment]
> FilterAndSortEnabled

Thank you so much :)

**Comment by davidegironi** [comment]
You are welcome ;)
