### ISSUE TITLE
Re-click on the filter button

### ISSUE THREAD

**Issue by manikandanece** [davidegironi/advanceddatagridview#7]
For an instance, I opened the filter menustrip by clicking the filter button.  The filter menu is now open.  If I want to close the filter menu, either I have to click on 'Cancel' button or I have to click somewhere else on the datagridview.  But we I re-click on the same filter button (of the column which already menustrip is open), the filter menustrip closes and opens again.  On this second click, it should only close and should not open again.
Note:  I dont know where to post suggestions, so I posted here.

**Comment by davidegironi** [comment]
Hello, thank you for this suggestions. Unluckly I can not repeat the behaviour you are describing here. Have you got a screencast for this?
