### ISSUE TITLE
How to use Advanced DataGridView Search Tool Bar???

### ISSUE THREAD

**Issue by SaryZainoun** [davidegironi/advanceddatagridview#71]
Please tell me how to link the Advanced Search Bar to the Advanced DataGridView, I couldn't find a way to link them.

**Comment by davidegironi** [comment]
Hello, you can find an example in the Sample project.

**Comment by SaryZainoun** [comment]
Never mind, I have figured it out using your provided sample.


Thank you very much. This is an awesome project.

**Comment by davidegironi** [comment]
That's great!
