### ISSUE TITLE
Calling .CleanFilterAndSort causes stackoverflow exception

### ISSUE THREAD

**Issue by acentrella13** [davidegironi/advanceddatagridview#74]
Hello,

I'm using the ADGV and if I have a user manually set a sort on a column, then aftwerward programmatically call .CleanFilterAndSort, a stackoverflow exception is generated.

See below stack..   thank you

System.StackOverflowException
  HResult=0x800703E9
  Message=Exception of type 'System.StackOverflowException' was thrown.

<HTML>
<head>
<title>Document</title></head>
<body>

  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Exception of type 'System.StackOverflowException' was thrown."} | System.StackOverflowException
  | ◢ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | Count | 0 | int
  | IsFixedSize | false | bool
  | IsReadOnly | false | bool
  | IsSynchronized | false | bool
  | ▶ Keys | {System.Collections.ListDictionaryInternal.NodeKeyValueCollection} | System.Collections.ICollection {System.Collections.ListDictionaryInternal.NodeKeyValueCollection}
  | ▶ SyncRoot | {System.Collections.ListDictionaryInternal} | object {System.Collections.ListDictionaryInternal}
  | ▶ Values | {System.Collections.ListDictionaryInternal.NodeKeyValueCollection} | System.Collections.ICollection {System.Collections.ListDictionaryInternal.NodeKeyValueCollection}
  | ▶ Non-Public members |   |  
  | ▶ Results View | Expanding the Results View will enumerate the IEnumerable |  
  | HResult | -2147023895 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "Exception of type 'System.StackOverflowException' was thrown." | string
  | Source | null | string
  | StackTrace | null | string
  | TargetSite | null | System.Reflection.MethodBase
  | ◢ Static members |   |  
  | ▶ Non-Public members |   |  
  | ▶ Non-Public members |   |  

</body>
</HTML>

**Comment by davidegironi** [comment]
Hello, I can't reproduce this error. It seems CleanFilterAndSort works on my tests.
Try using the sample project AdvancedDataGridViewSample, sort a column, then click on the "Clean Filter And Sort" button, it will call pragmatically the CleanFilterAndSort method. To me it works, both in net40 and net5.0. Let me know.

**Comment by acentrella13** [comment]
Thank you for looking in to this... did you have a user manually set a sort on a column first before calling the method?

**Comment by acentrella13** [comment]
![Capture](https://user-images.githubusercontent.com/59454754/141149520-5cf58da3-943e-483f-925b-bdcae4ad247b.PNG)

**Comment by davidegironi** [comment]
You're welcome.
A simple test could be:
1. Open the sample project
2. Click on a column header to sort it
3. Click the "Clean Filter And Sort" button
To run this test you have to download the code of this project.
You should also check that the SortStringChanged and FilterStringChanged event is not the cause of this problem.
Let me know.

**Comment by acentrella13** [comment]
Yes those two events are not being called or causing any kind of loopback... I understand the sample project works but as you can see in the attached photo above it triggers this exception.  My project is large, yet when the grid crashes it only has a few rows.  I can not currently explain the difference between the sample project and mine for they are calling the same method.

**Comment by acentrella13** [comment]
It might have something to do with the underlying bound dataview (dvOrders)... if I unbind prior, then clear it, then rebind this error does not occur...   as such:
                dgOrders.DataSource = null;
                dgOrders.CleanFilterAndSort();
                dgOrders.DataSource = dvOrders;

Since the dataview has filtering of its own, i wonder if that is causing an issue...there is filtering that is applied to the dataview, and then there are additional buttons to quick filter the datagrid, but since i don't have control over clearing the icon in the columnheader for a filtered or sorted col i'm calling cleanfilterandsort to clear it.

**Comment by davidegironi** [comment]
The CleanFilterAndSort method you use is the correct one to filter data. There's could be something related to the DataSource binded, as long as I'm not able to look at your code, I can't help you more.
One think could be "disable" the Filter/Sort-StringChanged event. If you haven't override those, you might do this (sample project contains an ovveride sample), there you can place a "stop" variable, like "if(doNotChangeUnderlineBindingSource) return;"... Hope this helps.
By the way, I'm using AVDG at least in one large (> 100 Forms, ~20Gb Db) project without issues.

**Comment by acentrella13** [comment]
Yes i trapped those changed events and they aren't fired when the CleanFilterAndSort method is called.  For now, un/rebinding seems to do the trick and the delay is slight.  It is comforting to know you are using AVDG with that size.  Thank you for your help.

**Comment by davidegironi** [comment]
You are welcome.
As a side note: if you want you can take a look at this project here: https://github.com/davidegironi/dentned where I use this component on top of an helper framework. There too, no problem ordering or filtering, as far as i know.

**Comment by acentrella13** [comment]
Will check it out thanks
