### ISSUE TITLE
Filter Box showing Rich text Format value from the SQL Server Database Table Column

### ISSUE THREAD

**Issue by SFAKHAN** [davidegironi/advanceddatagridview#75]
Hello,
I am saving a column in the Table as Rich Text Format value: 
{\rtf1\fbidis\ansi\ansicpg1252\deff0\deflang4105{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
\viewkind4\uc1\pard\ltrpar\f0\fs21 TEST TEST moved\f1\fs20\par
}
 
Now when I use ADGV to display data to the user, I am able to choose a "DataGridViewRichTextColumn" Column type to display the rich text without the RTF tags/code, but when the user tries to filter or Sort, the filter or Sort box/Window shows the RTF value from the Database. 

Is there a way to display only the plain text (Not RTF tag text) in the Filter/Sort dialog box? 

![image](https://user-images.githubusercontent.com/95777373/145278747-573319be-ff7a-4c59-a6e7-24799061930c.png)

**Comment by davidegironi** [comment]
Hello, Rich Text is not a supported format.
Anyway can you share a sample project?
An approach could be to override the ToString() method of your the data type of the column.

**Comment by SFAKHAN** [comment]
I have created a very basic project with only one ADGV containing only one RTF type column. There are two other class files that enables the RFT enabled ADGV column. The code of the form in:

using Microsoft.Office.Interop.Word;
using MigraDoc.DocumentObjectModel;
using MigraDoc.Rendering;
using PdfSharp.Drawing;
using PdfSharp.Drawing.Layout;
using PdfSharp.Pdf;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApp30
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            InitData();          
        }
        void InitData()
        {
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 1BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 2BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 3BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 4BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 5BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 6BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 7BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 8BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 9BOLD }{\f1\fs16\cf0 description}\par}}");
            this.adgv.Rows.Add(@"{\rtf1\deff0{\fonttbl{\f0 Times New Roman;}{\f1 Arial;}}{\colortbl\red0\green0\blue0;\red49\green105\blue198;\red255\green0\blue0;}{\*\listoverridetable}{\stylesheet {\ql\cf0 Normal;}{\*\cs1\cf0 Default Paragraph Font;}}{\sectd\pard\plain\ql{\b\f1\fs16\cf0 10BOLD }{\f1\fs16\cf0 description}\par}}");

        }
    }
}


H:\Sharmin_Temp\Code_Repository\Test_Code\WindowsFormsApp30\WindowsFormsApp30\RichTextBoxPrinter.cs
H:\Sharmin_Temp\Code_Repository\Test_Code\WindowsFormsApp30\WindowsFormsApp30\DataGridViewRichTextBoxColumn.cs
H:\Sharmin_Temp\Code_Repository\Test_Code\WindowsFormsApp30\WindowsFormsApp30\Form1.cs

**Comment by SFAKHAN** [comment]
I am using the two class files: 
DataGridViewRichTextBoxColumn.cs and
RichTextBoxPrinter.cs

to make the adgv to have RTF enabled column types. 

The gird displayes the data absolutely alright, but when I am trying to filter the data, I am unable to because the filter/Sort box is showing RTF data as opposed to text data. 

I am wondering if there is a way to manipulate/write a class to control what type of data is shown in the Filter/Sort boxes. 

If this is impossible, I will have to create two columns in the DB to store RTF and plain text data and just pull the plain text data for the ADGV. I think this is a very redundant way to approach this issue. 

Thank you so much for getting back so quickly. I really appreciate this.

**Comment by davidegironi** [comment]
You may try to override the ToString() method of your DataGridViewRichTextBoxCell class.
This is where the list for other than know typed nodes is populated: https://github.com/davidegironi/advanceddatagridview/blob/f81f0e10a4ab3285a82c41c1a30a61242ec367df/AdvancedDataGridView/MenuStrip.cs#L1099
If it does not work you have to download the ADGV source code and edit the code adding your class type, than  use your own version of ADGV.
Because Rich Text is not a standard type I will not add this to the ADGV master branch.

**Comment by SFAKHAN** [comment]
Where and how can I download the code for ADGV?

**Comment by SFAKHAN** [comment]
I am not sure what you mean by the "ToString() method of your DataGridViewRichTextBoxCell class". I am a new programmer and if you could explain a bit that would help greatly.  Thank you in advance.

**Comment by davidegironi** [comment]
You can download the code from here, from github. You can "git clone" this repository, or Download using the web button.
You can override the ToString method adding the following string
`public override string ToString () {
String s = "Get yor string from class, remove all the RichTextBox fancy"; // your code here
return s; }`
Take a look here for the override meaning: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/override
