### ISSUE TITLE
FilterStringChanged and SortStringChanged events are fired before filtering/sorting applied

### ISSUE THREAD

**Issue by will-scc** [davidegironi/advanceddatagridview#78]
In both `TriggerSortStringChanged()` and `TriggerFilterStringChanged()` the associated `StringChanged` events are fired before the filters have been applied to the datasource. This means that if you are subscribed to the those events, the view of the current filter state is always for the previous state.

An easy example of this is to check the `DataGridView.Rows.Count` property in the `FilterStringChanged` event - you will see that count is not the result of the filter string change that triggered the event:

- DataSource contains 100 records
- User selects filter that would return 50 records
- FilterStringChanged event is fired
- Checking `Rows.Count` in FilterStringChanged event shows 100 (current state)
- DataSource is filtered
- `Rows.Count` is now 50 (but we still think it's 100 from last FilterStringChanged event)

I believe the below change would resolve this.

```
/// <summary>
/// Trigger the filter string changed method
/// </summary>
public void TriggerFilterStringChanged()
{
    //call event handler if one is attached
    FilterEventArgs filterEventArgs = new FilterEventArgs
    {
        FilterString = _filterString,
        Cancel = false
    };

    //filter datasource
    if (filterEventArgs.Cancel == false)
    {
        if (this.DataSource is BindingSource bindingsource)
        {
            bindingsource.Filter = filterEventArgs.FilterString;
        }
        else if (this.DataSource is DataView dataview)
        {
            dataview.RowFilter = filterEventArgs.FilterString;
        }
        else if (this.DataSource is DataTable datatable)
        {
            if (datatable.DefaultView != null)
                datatable.DefaultView.RowFilter = filterEventArgs.FilterString;
        }
    }
   
   //Move this to after the filtering of datasource has been done
   if (FilterStringChanged != null)
        FilterStringChanged.Invoke(this, filterEventArgs);
}
```

**Comment by davidegironi** [comment]
Thank you for the suggestion.
Doing this mod will prevent the FilterString and SortString overload by external methods, things like the 'Filter column "string":' textbox in the sample project will stop working, without any furter modification the code that use this library I mean (the sample project or any other project using this library in this way).
I have to leave like so for backward compatibility.
What I can do is add a public Field to engage both the Filter and Sort event after or before the DataSource actions. And leave this before as default. Sounds good to you?

**Comment by will-scc** [comment]
Hi Davide,

Your suggestion sounds like a good idea.

**Comment by davidegironi** [comment]
I'll do this in the next days and let you know here.

**Comment by davidegironi** [comment]
Done. Take a look at this, let me know if it works to you:
https://file.io/lXr0Fiwz4e0n
Added public SortStringChangedInvokeBeforeDatasourceUpdate anb FilterStringChangedInvokeBeforeDatasourceUpdate
I've used setter and getter to private variables just for consistency with the already written code.

**Comment by will-scc** [comment]
Looks good to me! Thanks for your work on this project.
