### ISSUE TITLE
Question: Is there any way to have a custom filter applied programmatically rather than the UI?

### ISSUE THREAD

**Issue by peros550** [davidegironi/advanceddatagridview#79]
Thanks for this nice library. 

I would like to add custom filtering in addition to what the user may have selected through the UI. 

Is this possible?

**Comment by davidegironi** [comment]
Hello,
It's not possible, but you could set the Filter and Sort string like it's done in the Sample project (look at the  'Filter column "string":'). You can also Save and Restore filters.

**Comment by peros550** [comment]
I need to ask something more.  I used the LoadFilterAndSort(string filter, string sorting) to apply some custom filtering in addition to any existing filter applied so far and it worked. However, the datagridview object identified the manual filtering and deactivated all filtering UI. That makes sense, as it wouldn't be able to properly show to the user what filter is being applied. 

Then, I called Datagridview.CleanFilterAndSort() in an effort to remove all special filtering and enable again the the UI filtering. The filter was removed, but the UI remained deactivated. Any idea how could I solve this issue?

Many thanks

**Comment by davidegironi** [comment]
This should not happen. I cannot replicate your problem. Download the code from this repository. Run the AdvancedDataGridViewSample project. Do some filtering. Click on Save Current Filter And Sort button, then Clean Filter And Sort. Now recall the filter and sort saved using Filter saved, Sort saved, and Apply button. This should apply the filter, you should filtering blocked as you mention. But if you click again Clean Filter And Sort, the UI should be enabled again and the filter clean. Does it work with the Sample project? If so you can take a look at the code of the sample, to check if something different on your. If does not work... we have to investigate further.

**Comment by peros550** [comment]
The app works, I will check your code and compare it with what I do in my code. Thanks a lot for your help so far.

**Comment by peros550** [comment]
I found the difference in your code with mine. You used CleanFilterAndSort() while I used CleanFilter() 
The CleanFilterAndSort reactivates the UI. The CleanFilter does not. For me it's fine. Again many thanks!
