### ISSUE TITLE
Inconsistent naming for sort & filter enable/disable functions

### ISSUE THREAD

**Issue by xxbiohazrdxx** [davidegironi/advanceddatagridview#8]
In the AdvancedDataGridView class, we have 

```
public void DisableFilterAndSort(DataGridViewColumn column);
public void EnableFilterAndSort(DataGridViewColumn column);
```

But we also have

```
public void SetFilterEnabled(DataGridViewColumn column, bool enabled);
public void SetSortEnabled(DataGridViewColumn column, bool enabled);
```

As someone who had to read through the code to find out how things worked, these function names are inconsistent and cause confusion. Enable/DisableFilterAndSort completely disables the column header dropdown, and calling SetFilterEnabled will not turn on filtering.

Furthermore, Having SetFilter/SortEnabled accept a bool where earlier we have Enable/Disable as function names is unintuitive. My recommendation would be to change these functions to either all be

```
public void DisableFilterAndSort(DataGridViewColumn column);
public void EnableFilterAndSort(DataGridViewColumn column);
public void DisableFilter(DataGridViewColumn column);
public void EnableFilter(DataGridViewColumn column);
public void DisableSort(DataGridViewColumn column);
public void EnableSort(DataGridViewColumn column);
```

or

```
public void SetFilterAndSortEnabled(DataGridViewColumn column, bool enabled);
public void SetFilterEnabled(DataGridViewColumn column, bool enabled);
public void SetSortEnabled(DataGridViewColumn column, bool enabled);
```

The second honestly is probably the way to go, as it would make things easier to control if sort/filter is enabled programmatically by passing the value of, for example, a checkbox to the function.

**Comment by davidegironi** [comment]
Thank you for your suggestion.
For backward compatibility I prefer to add functions instead of removing. What do you think about adding just one function, the one below?

```
public void SetFilterAndSortEnabled(DataGridViewColumn column, bool enabled)
{
  if (enabled)
    EnableFilterAndSort(column);
  else
    DisableFilterAndSort(column);
}
```

**Comment by xxbiohazrdxx** [comment]
Good point on the backwards compatibility. That method looks good to me. You could also flag the older methods with the '[Obsolete]' sugar to generate warnings for those using the old methods and guide them towards the new one.

**Comment by davidegironi** [comment]
Thank you, committed.
