### ISSUE TITLE
StackOverflowException when filtering many DateTime nodes

### ISSUE THREAD

**Issue by will-scc** [davidegironi/advanceddatagridview#81]
When filtering a DateTime column with many nodes, the following line 917 in `AdvancedDataGridView.cs` will throw a StackOverflowException:

`bindingsource.Filter = filterEventArgs.FilterString;`

To reproduce:

* Update `DisplayItemsCounter` in the sample project to 10000
* Run the sample and attempt to filter `datetime` column by selecting half the top level nodes, e.g.:
![image](https://user-images.githubusercontent.com/31592644/160798700-03f57d05-217c-46b0-93b1-fa0ddbed1219.png)

I'm not sure why an especially long FilterString causes this exception, but it's obviously related to how the BindingSource applies the filter.

I have found from testing that if instead of constructing a filter string like this:

`(Convert([{0}], 'System.String') LIKE %'01/01/2033 18:34:18'% OR '%02/01/2033 18:54:38%')`

If we create it as an `IN` expression it works much more efficiently and doesn't throw the exception:

`(Convert([{0}], 'System.String') IN ('01/01/2033 18:34:18', '02/01/2033 18:54:38'))`

**Comment by will-scc** [comment]
You can see how I implemented this here: https://github.com/will-scc/advanceddatagridview/commit/73543661b0c71982245e8e8f6cb7e73b8e1abd6f

**Comment by davidegironi** [comment]
Thank you, I'm pretty busy this period, as soon as I have some time I'll give this an apply this to main branch and nuget package.

**Comment by will-scc** [comment]
I've got some of my users testing this change and it seems OK (at least for the way we use it). I'll continue to work on the TimeSpan filter string too and then create a pull request for you to review.

**Comment by davidegironi** [comment]
Merged. Thank you for your effort.
I've just reverted back to some lines for consistency with write style of this project.
https://github.com/davidegironi/advanceddatagridview/commit/a5fc7d1a828b13818ea8615c364af40ee0bf9b03
