### ISSUE TITLE
DateTime Filtering

### ISSUE THREAD

**Issue by Xounay1** [davidegironi/advanceddatagridview#84]
Hello,

When I'm trying to filter date or datetime columns, the filter form is displaying nodes like string.

Can you help me please ?

**Comment by davidegironi** [comment]
Hello, you need to have a BindingSource with a DataSource with DateTime type column in order to use the Date kind filter.
Take a look to the sample project as reference.

**Comment by Xounay1** [comment]
My Datasource is using datetime , my field in the DB is a datetime. 
![image](https://user-images.githubusercontent.com/82828212/165582588-5bddfe7a-0ad3-4d79-815b-3b3d7a172c6b.png)

My issue 👍 
![image](https://user-images.githubusercontent.com/82828212/165582845-741cffa5-175a-474d-b03f-ac56db8dd087.png)

**Comment by davidegironi** [comment]
You have to check the DataSource of the BindingSource attached to the DataGridView. Take a look at the sample project. Another sample you can look at is this porject here https://github.com/davidegironi/dentned

**Comment by Xounay1** [comment]
what should I check at the DataSource level ?
![image](https://user-images.githubusercontent.com/82828212/165587368-f93f2384-dd1b-4472-bbe7-21890ea08fe1.png)

In my datatable the column is set as System.DateTime, in the database the type is DateTime as well.

**Comment by davidegironi** [comment]
You should iterate each DataTables, and check for the DataColumn type.

**Comment by Xounay1** [comment]
I only have 1 datatable, 
![image](https://user-images.githubusercontent.com/82828212/165592805-de773e92-44bb-48c2-8abb-10db49bccabf.png)

I tryied to create a new simple project just doing a TOP (100) on a DateTime field from a simple Table, I'm experiencing the same issue.

Could it related to my OS culture info ? or to my datetime data format setup ?
HKEY_CURRENT_USER\ Control Panel\International\sShortDate
HKEY_CURRENT_USER\ Control Panel\International\sShortTime
HKEY_CURRENT_USER\ Control Panel\International\sTimeFormat

**Comment by Xounay1** [comment]
I also tried to create a simple project loading dynamically data from a SQL query(forcing to CAST AS DATE) to a datatable then filling the ADGV with the datatable, same result.
![image](https://user-images.githubusercontent.com/82828212/165639242-cf5801c7-4e51-42ca-8b1f-a46536d03e79.png)
