### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by leonardobuasso** [davidegironi/advanceddatagridview#87]
I am getting the data as follows the datatable is populated from an sql query
Private bs As New BindingSource
Private dtLote As DataTable
bs.DataSource = dtLote
flexADGV.DataSource = bs

I see high memory usage every time I load the flexADGV (advancedatagridview) The same does not happen when I use Microsoft's datagridview

Am I doing something wrong or is adavancedatagridview not monitoring memory usage?

Thank you

**Comment by davidegironi** [comment]
Hello, how many records (columns and rows) are you talking about?

**Comment by leonardobuasso** [comment]
2 Columns and 100 rows

**Comment by davidegironi** [comment]
That's nothing to load. It should works fast. 
What did you mean with "high memory usage"? How much?
You can download the actual git master brench, and try the sample project. Compare the memory usage with the last one.

**Comment by leonardobuasso** [comment]
Thanks for answering
What I mean is that the memory increases for each Query/Filter
Using the Visual Studio Diagnostic Tool I can see that it costs 750000 (bytes)
The problem is that the zuby objects keep piling up endlessly.
The difference I have with the master git is that it uses GC.Collect(); with a _timememoryusage_Tick Interval = 2000
This is correct?
Is the recommendation to use it every 2 seconds?

thank you

**Comment by davidegironi** [comment]
There have been a couple of memory leaks fixed on this project, as example you can take a look here: https://github.com/davidegironi/advanceddatagridview/issues/41
I've tested right now the memory usage of the component, I can not find any unusual behaviuor. The sample project on my PC runs using 35Mb, which is fine, also there is a memory test you can run, it will instantiate a few grids, you can set the test parameter on the sample project. Even after the test memory keep running on 45Mb.
Consider a few bytes of memory used is ok. Maybe I miss something, if you find it out just tell us here and I will check it.
Usually the garbage collector on .NET is run by the framework. I call it pragmatically just for test purpose, but you should not do this in you main project unless you have a reason.
