### ISSUE TITLE
Filter options disappearing

### ISSUE THREAD

**Issue by dGemini** [davidegironi/advanceddatagridview#88]
hello !

I have the following issue, using the advanceddatagridview  

My data is coming from an SQL query.  this datatable is then used as datasource of the advanceddatagridview, sometimes it could also be a dataview.

when I filter data, for instance on names out of the list presented when I click on the NAME heading, the filtering occurs correctly.  But when I click again on that NAME heading, the list presented holds only the names that I selected before.  

I can click on Clear filter or on Select All, after which the entire list is complete again, but that is not supposed to be the correct method.

simplyfied exemple in the image added :
![filter](https://user-images.githubusercontent.com/47326979/169835588-e6e969d5-6dbc-413a-b7c1-df154a02cc77.png)

What could I be doing wrong ?

thanks for your reply!
K.

**Comment by davidegironi** [comment]
Hello, you can use the SetChecklistTextFilterRemoveNodesOnSearchMode to change the filter mode of each column. Take a llok at the sample project, you can find an example there.  to call the SetChecklistTextFilterRemoveNodesOnSearchMode on the column.
