### ISSUE TITLE
A memory and user object leak is caused by binding a DataTable and creating a new BindingContext

### ISSUE THREAD

**Issue by Jonathan--V** [davidegironi/advanceddatagridview#89]
The code below is a Min-Reprex of an issue in a tool I'm working on. Of course, the tool doesn't create ADGVs in a tight loop like the example below, but it can sometime create and dispose of a huge number of ADGVs of the course of a single run.

I actually noticed the issue when the tool I'm working on hit the maximum number of GDI objects. I haven't been able to make a Min-Reprex for this (after a few hours of trying), but it seems to be caused by the assignment of the BindingContext to the ADGV in my tool. I think a fix for the memory and user object leak might well fix the GDI leak I'm experiencing too.

I've included how I noticed the problem below in case it helps, but any way of investigating memory issues of running code could work. 

Please let me know if any more information would be helpful.

**Repro steps**

1. Open Task Manager
2. Switch to Details tab
3. Right-click column headers. 
4. Click 'Select Columns'
5. Ensure 'Memory (active private working set)' and 'User objects' are checked and click 'ok'.
6. Run the below code.
7. Observe that memory usage and the number of user objects rapidly increase in number.
8. Stop the code.
9. Replace 'using AdvancedDataGridView dataGridView = new();' with 'using DataGridView dataGridView = new();'
10. Run the code.
11. Observe that memory usage and the number of User objects remain roughly constant.

**Expected Behaviour**

The memory usage and user objects created remain roughly constant with the below code.

**Code**

``` C#
using System.Data;
using System.Windows.Forms;
using Zuby.ADGV;

namespace BindingContextIssue
{
    public static class UserObjectLeakIssue
    {
        public static void KeepMakingADGVs()
        {
            using DataTable dataTable = new();
            dataTable.Columns.Add("Column A");
            while (true)
            {
                using AdvancedDataGridView dataGridView = new();
                dataGridView.DataSource = dataTable;
                dataGridView.BindingContext = new BindingContext();
            }
        }
    }
}
```

**Comment by davidegironi** [comment]
Hello,

Thank you for your feedback.

On net40 all object are disposed.
On net 5.0 don't. I suppose you are running net 5.0 version.

The issue is due to the way net 5.0 handle the objects.
Building ADGV pragmatically, only on net 5.0, seems does not trigger the "OnHandleDestroyed" method of AdvancedDataGridView.cs
Luckily this method is triggered when the ADGV is build and show in a form. At least it seems.

If you run the "Memory Test" from the sample project you can notice that the OnHandleDestroyed method is called whenever the form is closed.
The method is also called by your test but just if you run this on net40.

That is a tricky thing undrhood the net 5.0 framework. I have to investigate further to prevent this to happen. But luckily is not that bad, cause usually the ADGV is build and show.

**Comment by Jonathan--V** [comment]
Hi,

Thank you for your response.

You are correct that I am using .Net 5.0.

I understand that ADGVs are normally used from within a form: you are right that this particular issue occurs in an ADGV that is not attached to a form in the real tool I am working on. In the tool, the contents of the ADGV are used as part of an export of the view of the ADVG, sometimes without that ADVG being from a form. The same code for constructing an export is used regardless of whether the ADGV is one on a form or one created solely for the purpose of the export.

Is there a suitable workaround to force the ADGV to release its resources even when it is not built in a form?

I have tried calling OnHandleDestroyed directly (with a dummy EventArgs) but that does not seem to be sufficient. The same memory and user object leak occurs in the code below:

```
using System;
using System.Data;
using System.Windows.Forms;
using System.Reflection;
using Zuby.ADGV;

namespace BindingContextIssue
{
    public static class CallingOnHandleDestroyedDirectly
    {
        public static void KeepMakingADGVs()
        {
            using DataTable dataTable = new();
            dataTable.Columns.Add("Column A");
            while (true)
            {
                using AdvancedDataGridView dataGridView = new();
                dataGridView.DataSource = dataTable;
                dataGridView.BindingContext = new BindingContext();
                typeof(AdvancedDataGridView).GetMethod("OnHandleDestroyed", BindingFlags.Instance | BindingFlags.NonPublic).Invoke(dataGridView, new[] { new EventArgs() });
            }
        }
    }
}

```

**Comment by davidegironi** [comment]
I understand your needs.
You can run this way, seems to work to me.
Let me know.

```
        public static void KeepMakingADGVs()
        {
            using (DataTable dataTable = new DataTable())
            {
                dataTable.Columns.Add("Column A");
                System.Reflection.MethodInfo onHandleDestroyed = typeof(AdvancedDataGridView).GetMethod("OnHandleDestroyed", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
                while (true)
                {
                    AdvancedDataGridView dataGridView = new AdvancedDataGridView();
                    dataGridView.DataSource = dataTable;
                    dataGridView.BindingContext = new BindingContext();
                    dataGridView.Dispose();
                    onHandleDestroyed.Invoke(dataGridView, new[] { new EventArgs() });
                }
            }
        }
```

**Comment by Jonathan--V** [comment]
Disposing the ADGV prior to calling the OnHandleDestroyed method works great. This resolves the memory, user object and GDI leaks. Thank you very much for your help in finding this workaround.

**Comment by davidegironi** [comment]
That's great ;)
