### ISSUE TITLE
Calling SetFilterEnabled or SetSortEnabled after DisableFilterAndSort has been called does nothing

### ISSUE THREAD

**Issue by xxbiohazrdxx** [davidegironi/advanceddatagridview#9]
When 'DisableFilterAndSort' as is called for a column, the features of "Filter" and "Sort" cannot be turned on individually through 'SetFilterEnabled' or 'SetSortEnabled'

I think it might make more sense to remove 'DisableFilterAndSort' and 'EnableFilterAndSort' completely, and simply disable the individual "Filter" and "Sort" features exclusively through 'SetFilterEnabled' and 'SetSortEnabled'. If both are disabled, then hide the Filter/Sort UI.

**Comment by davidegironi** [comment]
Hello, thank you for suggestion, i will reply you in the other issue opened for almost the same reason.
