### ISSUE TITLE
How to change ColumHeadStyle?

### ISSUE THREAD

**Issue by oiDilyo** [davidegironi/advanceddatagridview#90]
I would like to change the column head back color to Gary.
I don`t know how to change this.

**Comment by davidegironi** [comment]
Hello, what do you mean with header color? Gary?

**Comment by oiDilyo** [comment]
I mean this.
![Color](https://user-images.githubusercontent.com/85553628/178881002-750acf68-56e0-4385-a493-c8b7a4423576.PNG)

**Comment by davidegironi** [comment]
Something like this, after the component is being initializated would work:

```
advancedDataGridView_main.ColumnHeadersDefaultCellStyle.BackColor = Color.Gray;
advancedDataGridView_main.EnableHeadersVisualStyles = false;
```
