### ISSUE TITLE
Memory Leakage Issue with contineous binding to different DataTables

### ISSUE THREAD

**Issue by YuLiangLin** [davidegironi/advanceddatagridview#92]
Hello,

I use this component in .netframework 4.8 winfrom projects, I recent found that there exists memory leakage issue, please see my test code below :

## TEST CODE
```csharp
private void TestLoop(int maxCount, DataGridView dgv)
{
	for (int i = 1; i <= maxCount; i++)
	{
		var memory = GC.GetTotalMemory(true);
		Console.Write($@"TestLoop {i}=>");

		dgv.DataSource = null;
		construct_test_dt(ref dt_Test, 100, 100);                        
		BindingSource bs = new BindingSource() { DataSource = dt_Test };
		dgv.DataSource = bs;

		memory = GC.GetTotalMemory(true);
		Console.WriteLine($@"MemoryUsage : {Math.Round(memory / (1024.0 * 1024.0), 2)} MB");
	}
}

private void construct_test_dt(ref DataTable dt, int columnSize, int rowSize)
{
	dt = new DataTable();
	if (columnSize < 1) columnSize = 1;
	if (rowSize < 1) rowSize = 1;
	for (int j = 0; j <= columnSize; j++)
	{
		dt.Columns.Add($@"col_{j}", typeof(int));
	}
	for (int i = 0; i <= rowSize; i++)
	{
		DataRow dr = dt.NewRow();
		foreach (DataColumn dc in dt.Columns)
		{
			dr[dc.ColumnName] = r.Next(0, 65535);
		}
		dt.Rows.Add(dr);
	}
}
```

When I use the TestLoop to test AdvancedDataGridView and watch its memore usage, its memoy usage continue grow up, and finally this datagridview crashed.

![image](https://user-images.githubusercontent.com/29618654/184498988-b7eda309-0005-4965-9adf-3056d10cd1b2.png)

I also upload this test project [here](https://github.com/YuLiangLin/advanceddatagridview/blob/master/ADGV_MemoryLeakageTest/Form1.cs)

This code works will with normal datagridview, please help check this issue, thanks.

**Comment by davidegironi** [comment]
Thank you for this feedback.
The reason for this leak is that the ADGV is never disposed, so internal structures always grow. I may take a look to see if there's a workaround, but for now you can dispose the ADGV and use a new one, that way you will not have leaks.

**Comment by YuLiangLin** [comment]
I found anonther important behavior, if I dont't set the DataSource = null, its memory wouldn't grow up so fast :
```csharp
private void TestLoop(int maxCount, DataGridView dgv)
{
	for (int i = 1; i <= maxCount; i++)
	{
		var memory = GC.GetTotalMemory(true);
		Console.Write($@"TestLoop {i}=>");

		//dgv.DataSource = null;
		construct_test_dt(ref dt_Test, 100, 100);                        
		BindingSource bs = new BindingSource() { DataSource = dt_Test };
		dgv.DataSource = bs;

		memory = GC.GetTotalMemory(true);
		Console.WriteLine($@"MemoryUsage : {Math.Round(memory / (1024.0 * 1024.0), 2)} MB");
	}
}
```
You can see that if we **don't set ADGV's DatSource = null**, its memory would grow up so fast :

![image](https://user-images.githubusercontent.com/29618654/184519807-b5112957-c055-4fbc-a2d7-b2a2388d2fce.png)


Here is side by side comparison chart :

![image](https://user-images.githubusercontent.com/29618654/184519853-61441ca5-b5c1-4b24-8a19-4869e8cf82bd.png)

The memory still grow continuously, but at least it wouldn't crash so fast.

[TestCode](https://github.com/YuLiangLin/advanceddatagridview/blob/master/ADGV_MemoryLeakageTest/Form1.cs)

Is there a way to dispose the internal structures before binding souce to ADGV?

**Comment by YuLiangLin** [comment]
I found that when I set DataSource = null, it will fire onColumnRemoved Event()

![image](https://user-images.githubusercontent.com/29618654/184520481-56ae3e33-4533-43f2-8678-bc12958c0629.png)

You will add the column header cell into _menuStripToDispose list, and its dipose event is inside OnHandleDestroyed()

![image](https://user-images.githubusercontent.com/29618654/184520525-7d411db7-3e26-467b-800c-0fcea17206c7.png)

So the _menuStripToDispose and _columnHeaderCellsToCleanEvents  continue grow up if we set DataSource = null and then assign new DataSources.

![image](https://user-images.githubusercontent.com/29618654/184520698-4040780e-9687-460a-b321-7749eebfbbcf.png)


I think it's better dispose it directly inside OnColumnRemoved()
```csharp
protected override void OnColumnRemoved(DataGridViewColumnEventArgs e)
{
	_filteredColumns.Remove(e.Column.Name);
	_filterOrderList.Remove(e.Column.Name);
	_sortOrderList.Remove(e.Column.Name);

	ColumnHeaderCell cell = e.Column.HeaderCell as ColumnHeaderCell;
	if (cell != null)
	{
		cell.SortChanged -= Cell_SortChanged;
		cell.FilterChanged -= Cell_FilterChanged;
		cell.FilterPopup -= Cell_FilterPopup;
		cell.CleanEvents();
		cell.MenuStrip.Dispose();
		//_columnHeaderCellsToCleanEvents.Add(cell);
		//_menuStripToDispose.Add(cell.MenuStrip);
	}
	base.OnColumnRemoved(e);
}
```
As you can see, the memory would raise at first loop, then keep at 4.73MB

![image](https://user-images.githubusercontent.com/29618654/184522182-c9683242-47a2-44ac-bcfd-e6bd9962f494.png)

Chart Comparison :

![image](https://user-images.githubusercontent.com/29618654/184522245-dd6ec080-5cd1-4d89-abdc-53157ce66ea8.png)

Please check the code change [here](https://github.com/davidegironi/advanceddatagridview/commit/3846eca25abfdf09fba44d069ecf7af6cc7184e2)

It could temporary solve memory leakage issue if assigin DataSource = null, the OnColumnRemoved event will dispose ColumnHeader Cell directly, but if don't do that and continue assign new DataSource to it, it still exists leakage issue.

I'll also try to figure out is there any way to prevent that issue.

**Comment by davidegironi** [comment]
Thank you for your help.
I've investigated further, think I've solved it. Today I've not time. Hopefully I will post here on monday with a suggested solution. I will ask you to check, then I will publish it as a new release fixed.

**Comment by davidegironi** [comment]
Hello, check this fix out. It should work
https://file.io/Poq7eGaAqGPc

Also notice a DataSource Memory Test was added to the AdvancedDataGridViewSample Project.

Let mw know.

**Comment by YuLiangLin** [comment]
> Hello, check this fix out. It should work https://file.io/Poq7eGaAqGPc
> 
> Also notice a DataSource Memory Test was added to the AdvancedDataGridViewSample Project.
> 
> Let mw know.

Hello, I'm sorry that I missed this message, I cannot access that file, could you upload it again?

**Comment by davidegironi** [comment]
Fine it here: https://file.io/N36MDF2Q1TnU
It should last 4 weeks

**Comment by YuLiangLin** [comment]
Hi,

I test it today, some feedbacks below :
1.If assign the datasouce to null first, and then binding to this ADGV's datasource, the memory will not continously increase.
2. If don't assign the datasouce to null first, and contineously binding new datatable to ADGV, it still have slightly leakage issue in my test project, I saw you add a timer to perform GC.Collect() every 2 seconds, and I did the same thing like you, and also set double buffered, please check the revised code below : https://file.io/Ew6k8jrVUUvW

![image](https://user-images.githubusercontent.com/29618654/188319616-29ac9838-bf57-4f15-b9d2-4da3dedde804.png)

The second one it's not a critical issue, so I think this issiue could be closed, please help make this change to that ADGV nuget package, thanks for your help.

**Comment by davidegironi** [comment]
I think this last one could be due to some DataSource disposing. Anyone that's a minor thing.
Fix merged to main brench, draft a new release to nuget too.
Thank you for your help.
