### ISSUE TITLE
Cannot access a disposed object (1.2.27307.7)

### ISSUE THREAD

**Issue by lstoeckert** [davidegironi/advanceddatagridview#94]
I've been using your AdvancedDataGridView without issues for a long time (great job).  But with the latest build, I've started getting an error in all of my implementations of it.  When the 'down arrow' for a column is pressed I get a "Cannot access a disposed object.' and it calls out the object 'MenuStrip'.  If I revert back to the previous version (.6), the problem goes away.

![Screenshot 2022-09-13 075533](https://user-images.githubusercontent.com/63424693/189894774-0f9f72db-708b-4654-a3c2-ff402c63e675.png)
[Stacktrace.txt](https://github.com/davidegironi/advanceddatagridview/files/9556799/Stacktrace.txt)

**Comment by davidegironi** [comment]
Hello @lstoeckert 
Thanks for let me know.
I think this is a bug opened from the last issue fix https://github.com/davidegironi/advanceddatagridview/issues/92 
Indeed for this issue MenuStrip are disposed OnDataSourceChanged
I've checked it on the sample project but I'm not able to reproduce your error.
Can you prepare a sample project to reproduce this error?

**Comment by lstoeckert** [comment]
I created a small VB sample that reproduces the problem.  
[ADGVTest.zip](https://github.com/davidegironi/advanceddatagridview/files/9557151/ADGVTest.zip)

**Comment by davidegironi** [comment]
I'm working on this, let me Reopen this issue. I think I get the point...

**Comment by davidegironi** [comment]
The problem is that you are change the datasource after the columns has been added to datasource, and also your datatable has already binded a datasource.

Taking your example as source, the following way you get the problem you have:
```
Dim bsTest As New BindingSource With {.DataSource = dtTest}
dgvTest.DataSource = bsTest
dtTest.Columns.Add("Column1", GetType(String))
dtTest.Columns.Add("Column2", GetType(String))
dtTest.Columns.Add("Column3", GetType(String))

```
the following you have not
```
Dim bsTest As New BindingSource With {.DataSource = dtTest}
dtTest.Columns.Add("Column1", GetType(String))
dtTest.Columns.Add("Column2", GetType(String))
dtTest.Columns.Add("Column3", GetType(String))
dgvTest.DataSource = bsTest
```

But, I've fixed this inside ADGV to let you use your current way, cause it's also a legitimate way.
I basically check for _menuStripToDispose list for legitimate columns even on OnDataSourceChanged before disposing the cells, so OnDataSourceChanged method became like below:
```
protected override void OnDataSourceChanged(EventArgs e)
{
    foreach (DataGridViewColumn column in Columns)
    {
        ColumnHeaderCell cell = column.HeaderCell as ColumnHeaderCell;
        _menuStripToDispose = _menuStripToDispose.Where(f => f != cell.MenuStrip).ToList();
    }
    foreach (MenuStrip menustrip in _menuStripToDispose)
    {
        menustrip.Dispose();
    }
    _menuStripToDispose.Clear();

    base.OnDataSourceChanged(e);
}
```

Please check the library you find at this address, tell me if it works for you too, if so I will publish the fix on nuget as soon as possible.

https://file.io/KW9A420aLAPR

**Comment by lstoeckert** [comment]
Davide,

 

Thank you for looking into this.  I’ve downloaded the file you provided, unfortunately, it is a raw code file and I’m not sure how to incorporate that into my program.  Would it be possible to just get the updated DLL?

 

 

Regards,

 

Lee

**Comment by davidegironi** [comment]
Unzip the file, you should see the AdvancedDataGridView.sln file.
Open this solution file with Visual Studio (you should have 2019). Then build it using Visual Studio. You should find the DLL in the usual Debug or Release folder, depending on the kind of compilation you have done.

**Comment by lstoeckert** [comment]
Davide,

 

I’ve been trying to do this.  I can’t compile your project ‘as is’ because it refers to .Net 4.0 which I don’t have and the SDK is no longer available.  When I remove the 4.0 from your project and compile it, the resulting DLL turns out not to be the one that my project is using from the NuGet package, for some reason, it is using the 4.0 and I can’t switch it to the 5.0.

 

Suggestions?

 

 

Regards,

 

Lee

**Comment by davidegironi** [comment]
Here you can find compiled dll for both net40 and net5 https://file.io/uXbZp5ToPFJb

**Comment by lstoeckert** [comment]
Thank you.  I’ve installed these DLLs and the problem is resolved.  Thank you for all your help!

 

 

Regards,

 

Lee

**Comment by lstoeckert** [comment]
I tested my sample project with these DLLs and the problem was resolved.  I also tested with one of the larger projects and the problem there is also resolved.  Thank you so much for addressing this issue and for the great product!  I assume they'll be a update to NuGet for .8 shortly?

**Comment by davidegironi** [comment]
Fix published to master branch and nuget.
Thank you for your feedback and testing.
