### ISSUE TITLE
Designer-Generated Columns do not have type-specific filtering

### ISSUE THREAD

**Issue by ChristopherGuay** [davidegironi/advanceddatagridview#95]
Hi!
I am currently having an issue getting the type-dependent filtering behaviour to work with pre-defined columns (generated by the designer).

Columns created in the designer result in MenuStrips with datatype = null and only ever have the text custom filtering. Columns that are autogenerated result in MenuStrips with the appropriate datatype and the type-dependent filtering enabled. There are many cases where Auto-Generated columns is not appropriate in our use case so allowing the columns to be defined in the designer is enormously valuable.

I have looked at the sample code as suggested in #10 
Changing the events for FilterStringChanged as suggested there does not appear to affect this behaviour at all.

It appears that once the data type of a column has been determined (in this case determined to be null because the data has not been loaded yet), it cannot be changed (due to access levels and the automatic nature of creating MenuStrips).

Please let me know if there is anything I can do so that the MenuStrip for my designer-generated columns can be the appropriate type.

Chris

**Comment by davidegironi** [comment]
Hello, once assigned the type of the column can not be changed.
What about building a DataSource and binding it to the GridView? It's simpler than the design, and you can use the designer to build a DataSource too (depending on the db you are using). To me that's the faster thing.
If you create a small sample project I can take a look at your code, but I suppose there's not much to do.

**Comment by ChristopherGuay** [comment]
In looking at the source code I don't understand why the type of the column cannot be changed. It appears that if the MenuStrip or ColumnHeaderCell objects were accessible then either could be made null and recreated. Auto-generated columns have their types detected dynamically when they are added to the DataGridView, could the OnColumnAdded event or very similar not be able to be triggered some other way? Are you able to explain the limitation?

Additionally I have tried exploring your solution of using a bound DataSource but this does not work with my application. I still do not get the ability to manually define visible columns (or do other similar actions) ahead of runtime. Additionally there are a number of cases where we perform some action to the data, combine data from multiple databases, or have a dynamic amount of columns, where it does not seem possible or practical to define with a bound DataSource.

**Comment by davidegironi** [comment]
Hello. If you take a look at the MenuStrip.cs constructor, you should see that datatype defines the way the menu is built. Of course one can made DataType settable by a getter/setter and change the code in such a way that the components dynamically react to DataType change, but that's not how it works now.
So you can do this, but a deeper analysis of the code and a few changes are needed.
You can take a look at a couple of project I've built that uses ADGV like https://github.com/davidegironi/dentned or https://github.com/davidegironi/doctcod
