### ISSUE TITLE
Change languaje to Spanish

### ISSUE THREAD

**Issue by marcoahp** [davidegironi/advanceddatagridview#97]
How can I change language to Spanish es-ES?
You can apply the same as es-AR which somebody have sent to es-ES

**Comment by davidegironi** [comment]
Hello,

Take a look at the sample project (AdvancedDataGridViewSample), you can use the SetTranslations Method, if you have a file (suppose lang.json) you can use like this:
```
if (_testtranslationsFromFile)
{
    AdvancedDataGridView.SetTranslations(AdvancedDataGridView.LoadTranslationsFromFile("lang.json"));
    AdvancedDataGridViewSearchToolBar.SetTranslations(AdvancedDataGridViewSearchToolBar.LoadTranslationsFromFile("lang.json"));
}
```

If you want to send me a "lang_es-ES.json" file I will add to the sample project, so that other people can use that.

**Comment by marcoahp** [comment]
Hi,

I’ve done it and it works fine. I send you the language file.

It would be great if it change language with the system language without settranslations command.

Best regards,

Marco

 

De: Davide Gironi ***@***.***> 
Enviado el: miércoles, 5 de octubre de 2022 11:44
Para: davidegironi/advanceddatagridview ***@***.***>
CC: marcoahp ***@***.***>; Author ***@***.***>
Asunto: Re: [davidegironi/advanceddatagridview] Change languaje to Spanish (Issue #97)

 

Hello,

Take a look at the sample project (AdvancedDataGridViewSample), you can use the SetTranslations Method, if you have a file (suppose lang.json) you can use like this:

if (_testtranslationsFromFile)
{
    AdvancedDataGridView.SetTranslations(AdvancedDataGridView.LoadTranslationsFromFile("lang.json"));
    AdvancedDataGridViewSearchToolBar.SetTranslations(AdvancedDataGridViewSearchToolBar.LoadTranslationsFromFile("lang.json"));
}

If you want to send me a "lang_es-ES.json" file I will add to the sample project, so that other people can use that.

**Comment by davidegironi** [comment]
Hello,

You can attache here in a post the language file, I will add the the next commit.
I prefer to leave outside the change language logic. This way one can set a language for the desktop project is building independently from the system language.
You can check this stackoverflow here to detect the system language and select the language file according to it: https://stackoverflow.com/questions/5710127/get-operating-system-language-in-c-sharp
