### ISSUE TITLE
Localization not working for every text

### ISSUE THREAD

**Issue by MartinErdely** [davidegironi/advanceddatagridview#98]
For some reason when I tried to setup hungarian localization, only certain texts got replaced. Tried the same way with the included italian lang file and the results were the same.

Picture of the error:
![localization_error](https://user-images.githubusercontent.com/79600066/201521841-db4b2f98-d70a-44b1-83ad-9ac50d158ff5.png)

Picture of the initialization:
![image](https://user-images.githubusercontent.com/79600066/201521923-8ac3f38d-6557-4e07-a0a3-cc3ba97cfad0.png)

Hungarian localization i made:
>{
  "ADGVSortDateTimeASC": "Rendezés dátum szerint (növekvő)",
  "ADGVSortDateTimeDESC": "Rendezés dátum szerint (csökkenő)",
  "ADGVSortBoolASC": "Rendezés Hamis/Igaz sorrendben",
  "ADGVSortBoolDESC": "Rendezés Igaz/Hamis sorrendben",
  "ADGVSortNumASC": "Rendezés méret szerint (növekvő)",
  "ADGVSortNumDESC": "Rendezés méret szerint (csökkenő)",
  "ADGVSortTextASC": "Rendezés (A-Z)",
  "ADGVSortTextDESC": "Rendezés (Z-A)",
  "ADGVAddCustomFilter": "Egyéni szűrő hozzáadása",
  "ADGVCustomFilter": "Egyéni szűrő",
  "ADGVClearFilter": "Szűrő törlése",
  "ADGVClearSort": "Rendezés törlése",
  "ADGVButtonFilter": "Szűrő",
  "ADGVButtonUndofilter": "Mégse",
  "ADGVNodeSelectAll": "(Az összes kijelölése)",
  "ADGVNodeSelectEmpty": "(Üres)",
  "ADGVNodeSelectTrue": "Igaz",
  "ADGVNodeSelectFalse": "Hamis",
  "ADGVFilterChecklistDisable": "Szűrési lista le van tiltva",
  "ADGVEquals": "egyenlő",
  "ADGVDoesNotEqual": "nem egyenlő",
  "ADGVEarlierThan": "korábban mint",
  "ADGVEarlierThanOrEqualTo": "korábban mint vagy pontosan",
  "ADGVLaterThan": "később mint",
  "ADGVLaterThanOrEqualTo": "később mint vagy pontosan",
  "ADGVBetween": "között",
  "ADGVGreaterThan": "nagyobb, mint",
  "ADGVGreaterThanOrEqualTo": "nagyobb vagy egyenlő",
  "ADGVLessThan": "ksiebb, mint",
  "ADGVLessThanOrEqualTo": "kisebb vagy egyenlő",
  "ADGVBeginsWith": "kezdete",
  "ADGVDoesNotBeginWith": "nem kezdete",
  "ADGVEndsWith": "vége",
  "ADGVDoesNotEndWith": "nem vége",
  "ADGVContains": "tartalmaz",
  "ADGVDoesNotContain": "nem tartalmaz",
  "ADGVInvalidValue": "Érvénytelen érték",
  "ADGVFilterStringDescription": "Sorok megjelenítése ahol az érték {0} \"{1}\"",
  "ADGVFormTitle": "Egyéni szűrő",
  "ADGVLabelColumnNameText": "Sorok megjelenítése ahol",
  "ADGVLabelAnd": "És",
  "ADGVButtonOk": "OK",
  "ADGVButtonCancel": "Mégse",
  "ADGVSTBLabelSearch": "Keresés:",
  "ADGVSTBButtonFromBegin": "Előről",
  "ADGVSTBButtonCaseSensitiveToolTip": "Kis- és nagybetű érzékeny",
  "ADGVSTBButtonSearchToolTip": "Következő",
  "ADGVSTBButtonCloseToolTip": "Elrejt",
  "ADGVSTBButtonWholeWordToolTip": "Teljes egyezés keresése",
  "ADGVSTBComboBoxColumnsAll": "(Összes oszlop)",
  "ADGVSTBTextBoxSearchToolTip": "Keresési érték"
}

**Comment by davidegironi** [comment]
Hello,

at a first look it seems there's an error in your file.
Check out the line:
"ADGVFilterStringDescription": "Sorok megjelenítése ahol az érték {0} "{1}"",
it shoul be
"ADGVFilterStringDescription": "Sorok megjelenítése ahol az érték {0} \"{1}\"",

**Comment by MartinErdely** [comment]
Yeah I have it like that, I just didn't see that in my comment it is also missing due to githubs formating. It's still not working properly tho, so I'm now trying to figure out the differences in our projects, cause if I include the hungarian lang file into your project it works like a charm.

**Comment by MartinErdely** [comment]
Columns created in the designer seems to be the issue, I managed to solve the problem by creating everything dynamically. However I got mixed results during testing, I can't say for completely sure what caused the issue, sometimes it was pretty random. Overall my issue is now solved, so I close this.

**Comment by davidegironi** [comment]
Great, let me know if you find the root cause of the problem.

**Comment by ltob** [comment]
> Columns created in the designer seems to be the issue, I managed to solve the problem by creating everything dynamically. However I got mixed results during testing, I can't say for completely sure what caused the issue, sometimes it was pretty random. Overall my issue is now solved, so I close this.

If the columns are created in the designer, you need to call text localization BEFORE InitializeComponent() in the constructor of the form with AdvancedDataGrid...

**Comment by davidegironi** [comment]
@ltob Thanks for clarification, it may help other people.
