### ISSUE TITLE
Restore Sort and Filter strings

### ISSUE THREAD

**Issue by SteStal** [davidegironi/advanceddatagridview#99]
I have a DataTable bound to an AdvancedDataGrid. I persist the SortString and FilterString in a XML file when closing the app.
I want to restore the last used Sort and Filter strings at next app start.
I set :
myresultstable.DefaultView.Sort = savedSortString
myresultstable.DefaultView.RowFilter = savedFilterString
This works fine logically, but the AdvancedDataGridView context menu selections and the table column icons (arrow&filter) are not updated. How can I do that? Thanks

**Comment by davidegironi** [comment]
Hello,
filter and sort history internally is not recorded to final formatted strings. Top menu images are based on filter internal history. In the actual version there's no way to implement this. The only method available is the LoadFilterAndSort, which will assign the Filter and Sort string to DataTable and disable the icons.
If you are going to implement this please let me know.

**Comment by SteStal** [comment]
Thank you very much for you prompt reply.
Sorry to hear it's not possible without code change.

**Comment by peros550** [comment]
This is quite useful feature. I am using your proposed method that deactivates the icons and although is works nice, it does “break” the logic and user cannot continue playing with filters.

**Comment by davidegironi** [comment]
You are right. I also kinda know how to implement this, but it takes a little of time, and I'm at present full time engaged in many other project, biggest of it my home renovation which I'm actively working as carpenter and so on :-/ Sorry about that

**Comment by peros550** [comment]
I understand and I wish you all the best with health and success for your projects in 2023. Of course life comes first :)
